<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tcbpla extends Model
{
    protected $fillable = [
        'CODEMP',
        'CTACTB',
        'GRAU',
        'DESCRCTA',
        'ANALITICA',
        'CENCUSOBRIG',
        'CONVSALDOMOEDA',
        'DTBASECONVMOEDA',
        'CODCTACTBPAI',
        'ATIVA',
        'PRODUTO',
        'PLANTA',
        'PROCESSO',
        'BEMORIGINAL',
        'BEMRESREAV',
        'BEMOUTROS',
        'OBSERVACOES',
        'PODELANCTOMANUAL',
        'DTINCLUSAO',
        'CODGRUPOCTA',
        'CODCTAREF',
        'RAZAOAUXSPED',
        'CODCTACTBSUBST',
        'DTINATIV',
        'CODUSU',
        'DTALTER',
        'PROJOBRIG',
        'LALUR',
        'LALUR_A',
        'TIPSALALUR',
        'CODCTAREF_FCONT',
        'TABELA',
        'CODRAZAUX',
        'DISPSPED',
        'NATUREZAEFD',
        'LALUR_A_CRED',
        'TABELACRED',
        'RECDESP',
        'CLASSIFIRPJ',
        'CLASSIFCSLL',
        'ADICOESIRPJ',
        'CONRESULTIRPJ',
        'EXCLUSOESIRPJ',
        'PAT4IRPJ',
        'ZERACRIRPJ',
        'ADICOESCSLL',
        'CONRESULTCSLL',
        'EXCLUSOESCSLL',
        'ZERACRCSLL',
        'CODLALURB',
        'INDTRIBLALURB',
        'CODCONTA',
        'DESCRCONTA',
        'AD_IDEXTERNO',
    ];
}