<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTgfparTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('TGFPAR', function (Blueprint $table) {
            $table->integer('CODVEND')->length(5)->default(0);
            $table->string('NOMEPARC')->length(80);
            $table->string('RAZAOSOCIAL')->length(80)->nullable();
            $table->string('TIPPESSOA')->length(1);
            $table->integer('CODPARCMATRIZ')->length(10)->nullable()->default(0);
            $table->integer('CODEND')->length(10)->default(0);
            $table->string('NUMEND')->length(6)->nullable();
            $table->string('COMPLEMENTO')->length(30)->nullable();
            $table->integer('CODBAI')->length(10)->default(0);
            $table->integer('CODCID')->length(10)->default(0);
            $table->integer('CODREG')->length(10)->default(0);
            $table->string('CEP')->length(8)->nullable();
            $table->string('CAIXAPOSTAL')->length(10)->nullable();
            $table->string('TELEFONE')->length(13)->nullable();
            $table->integer('RAMAL')->length(5)->nullable()->default(0);
            $table->string('FAX')->length(13)->nullable();
            $table->string('EMAIL')->length(80)->nullable();
            $table->datetime('DTCAD')->length(7);
            $table->datetime('DTALTER')->length(7);
            $table->datetime('DTNASC')->length(7)->nullable();
            $table->datetime('DTULTCONTATO')->length(7)->nullable();
            $table->datetime('DTULTNEGOC')->length(7)->nullable();
            $table->string('IDENTINSCESTAD')->length(16)->nullable();
            $table->string('INSCESTADNAUF')->length(16)->nullable();
            $table->string('CGC_CPF')->length(14)->nullable();
            $table->integer('CODTAB')->length(5)->nullable()->default(0);
            $table->integer('PRAZOCONTATO')->length(5)->nullable()->default(0);
            $table->integer('PRAZOPAG')->length(5)->nullable()->default(0);
            $table->integer('TOLERINADIMP')->length(5)->nullable()->default(0);
            $table->string('CLIENTE')->length(1)->default('S' );
            $table->string('FORNECEDOR')->length(1)->default('N' );
            $table->string('TRANSPORTADORA')->length(1)->default('N' );
            $table->string('VENDEDOR')->length(1)->default('N' );
            $table->string('AGENCIA')->length(1)->default('N' );
            $table->integer('CODTIPPARC')->length(10)->default(0);
            $table->string('CODCTABCO')->length(17)->nullable();
            $table->string('CODAGE')->length(5)->nullable();
            $table->integer('CODBCO')->length(5)->default(0);
            $table->string('NOMEAGE')->length(19)->nullable();
            $table->integer('CODCTACTB')->length(10)->nullable()->default(0);
            $table->integer('CODCTACTB2')->length(10)->nullable()->default(0);
            $table->string('CLASSIFICMS')->length(1)->nullable();
            $table->string('TARE')->length(1)->default('N' );
            $table->string('IPIINCICMS')->length(1)->default('N' );
            $table->string('RETEMISS')->length(1)->default('N' );
            $table->string('RETEMINSS')->length(1)->default('N' );
            $table->string('CONTACESSO')->length(30)->nullable();
            $table->string('SITUACAO')->length(1)->nullable()->default('B');
            $table->string('OBSERVACOES')->length(4000)->nullable();
            $table->string('ATIVO')->length(1)->default('S' );
            $table->integer('CODANT')->length(10)->nullable()->default(0);
            $table->integer('CODCTABCOINT')->length(5)->nullable()->default(0);
            $table->string('GRUPOAUTOR')->length(30)->nullable();
            $table->float('LIMCRED')->length(126)->nullable();
            $table->string('BLOQUEAR')->length(1)->default('N' );
            $table->string('SELECIONADO')->length(1)->nullable();
            $table->string('MOTBLOQ')->length(4000)->nullable();
            $table->string('EVENDA')->length(1)->default('N' );
            $table->string('ECOMPRA')->length(1)->default('N' );
            $table->string('HOMEPAGE')->length(255)->nullable();
            $table->string('CTAADIANT')->length(1)->default('N' );
            $table->integer('CODASSESSOR')->length(5)->default(0);
            $table->string('INSCMUN')->length(16)->nullable();
            $table->string('CALCINSS')->length(1)->default('N' );
            $table->integer('CODUSU')->length(5)->default(0);
            $table->string('RETEMPIS')->length(1)->default('N' );
            $table->string('RETEMCOFINS')->length(1)->default('N' );
            $table->string('RETEMCSL')->length(1)->default('N' );
            $table->string('USUARIO')->length(1)->nullable()->default('N');
            $table->string('CEI')->length(12)->nullable();
            $table->float('LIMCREDMENSAL')->length(126)->nullable();
            $table->integer('CODTABST')->length(5)->nullable()->default(0);
            $table->integer('QTDMAXTITVENCIDOS')->length(5)->nullable()->default(0);
            $table->string('TEMIPI')->length(1)->default('S' );
            $table->string('ALUNO')->length(1)->nullable();
            $table->string('PROFESSOR')->length(1)->nullable();
            $table->float('DESCFIN')->length(126)->nullable();
            $table->string('DESCBONIF')->length(1)->default('L' );
            $table->string('IMPLAUDOLOTE')->length(1)->default('N' );
            $table->integer('DIASEM')->length(5)->nullable()->default(0);
            $table->string('MEDICO')->length(1)->default('N' );
            $table->string('TIPOFATUR')->length(1)->default('L' );
            $table->integer('DIASVARPAGTO')->length(5)->nullable()->default(0);
            $table->string('CODUNIMED')->length(17)->nullable();
            $table->integer('CODCRED')->length(10)->nullable()->default(0);
            $table->float('PERCCUSVAR')->length(126)->nullable();
            $table->string('MOTORISTA')->length(1)->default('N' );
            $table->string('NATUREZAOPERDES')->length(2)->nullable();
            $table->string('SERIENFDES')->length(4)->nullable();
            $table->string('MODELONFDES')->length(2)->nullable();
            $table->string('DESCSTIVA')->length(1)->default('S' );
            $table->integer('CSTIPIENT')->length(5)->nullable()->default(0);
            $table->integer('CSTIPISAI')->length(5)->nullable()->default(0);
            $table->integer('CODEMP')->length(5)->nullable()->default(0);
            $table->float('VLRMINPEDCPA')->length(126)->nullable();
            $table->integer('QTDMAXPEDCPA')->length(10)->nullable()->default(0);
            $table->string('OPERLOGIST')->length(1)->default('N' );
            $table->string('AGRONOMO')->length(1)->default('N' );
            $table->string('PRODUTORTEMNF')->length(1)->default('S' );
            $table->float('POTENCIALNEG')->length(126)->nullable();
            $table->string('EMAILNFE')->length(255)->nullable();
            $table->string('TIPANEXONFE')->length(1)->default('X' );
            $table->string('ORDSUBST')->length(1)->nullable();
            $table->float('MAXCREDINDENIZ')->length(126)->nullable();
            $table->float('MAXDEBINDENIZ')->length(126)->nullable();
            $table->float('SALDOINDENIZ')->length(126)->nullable();
            $table->string('FLEX')->length(1)->default('S' );
            $table->string('SIMPLES')->length(1)->default('N' );
            $table->string('SEXO')->length(1)->nullable();
            $table->integer('NURESPPERG')->length(10)->nullable()->default(0);
            $table->integer('NURESPPERGFECH')->length(10)->nullable()->default(0);
            $table->integer('CODROTA')->length(10)->nullable()->default(0);
            $table->integer('CODCTACTB3')->length(10)->nullable()->default(0);
            $table->integer('CODCTACTB4')->length(10)->nullable()->default(0);
            $table->integer('CODUSUCOBR')->length(5)->default(0);
            $table->string('AGRUPAR')->length(1)->nullable();
            $table->string('EMAILDANFE')->length(1)->default('N' );
            $table->string('VALDESCGRDCAR')->length(1)->nullable();
            $table->string('AGRUPBOLEMPDIF')->length(1)->nullable();
            $table->float('PERCREDINSS')->length(126)->nullable();
            $table->string('PERMITECORTE')->length(1)->default('S' );
            $table->string('INDNATRET')->length(2)->nullable();
            $table->string('STATUSEDZ')->length(1)->default('P' );
            $table->string('SITRECEITA')->length(1)->default('I' );
            $table->string('SITSINTEGRA')->length(1)->default('I' );
            $table->string('SITCCF')->length(1)->default('I' );
            $table->string('USATABCRFORN')->length(1)->default('N' );
            $table->integer('QTDPEDPRZMED')->length(10)->nullable()->default(0);
            $table->integer('DIASPEDPRZMED')->length(10)->nullable()->default(0);
            $table->string('ARTPRECAD')->length(1)->default('N' );
            $table->string('GERCTRCAUTO')->length(1)->default('N' );
            $table->integer('CODLOCALPADRAO')->length(10)->default(0);
            $table->float('SALDODISP')->length(126)->nullable();
            $table->float('PROVACRESC')->length(126)->nullable();
            $table->string('EXIGELAUDOPRD')->length(1)->nullable();
            $table->string('MEIRJ')->length(1)->nullable();
            $table->string('ENTREGAENDCONTATO')->length(1)->default('N' );
            $table->integer('CODEMPPARC')->length(5)->nullable()->default(0);
            $table->string('RETSTVENDA')->length(1)->default('N' );
            $table->string('LATITUDE')->length(255)->nullable();
            $table->string('LONGITUDE')->length(255)->nullable();
            $table->string('TIPOGERBOLETO')->length(1)->default('I' );
            $table->float('PERCJURO')->length(126)->nullable();
            $table->float('PERCMULTA')->length(126)->nullable();
            $table->string('TIPJURO')->length(1)->nullable();
            $table->float('PERCDESCESPECIAL')->length(126)->nullable();
            $table->integer('CODEMPPREF')->length(5)->nullable()->default(0);
            $table->string('SITESPECIALRESP')->length(2)->nullable();
            $table->string('MOTNAORETERISSQN')->length(2)->nullable();
            $table->integer('SITCADSEFAZ')->length(5)->nullable()->default(0);
            $table->datetime('DHCADSEFAZ')->length(7)->nullable();
            $table->float('ALIQISSRETSIMPLES')->length(126)->nullable();
            $table->string('IDESTRANGEIRO')->length(20)->nullable();
            $table->string('TIPGERBOLCENT')->length(1)->nullable();
            $table->string('COMOCONHECEU')->length(100)->nullable();
            $table->string('TIPOGERBOLETODUP')->length(1)->default('I' );
            $table->string('BOLDESTEMAIL')->length(1)->default('A' );
            $table->integer('TPASSINANTE')->length(5)->nullable()->default(0);
            $table->string('APLICLEITRANSP')->length(1)->default('N' );
            $table->float('VENDAMIN')->length(126)->nullable();
            $table->integer('CODENQIPIENT')->length(5)->nullable()->default(0);
            $table->integer('CODENQIPISAI')->length(5)->nullable()->default(0);
            $table->string('ENVIPEDEMAILTOP')->length(1)->default('A' );
            $table->string('INTEGRAECONECT')->length(1)->default('N' );
            $table->string('SENHAECONECT')->length(32)->nullable();
            $table->string('PRAZOPARCECONECT')->length(32)->nullable();
            $table->integer('BASEPRAZOECONECT')->length(5)->default(0);
            $table->string('PARCELAMECONECT')->length(32)->nullable();
            $table->integer('BASEPARCELECONECT')->length(5)->default(0);
            $table->integer('DIAFECHAECONECT')->length(5)->nullable()->default(0);
            $table->integer('DIAPAGTOECONECT')->length(5)->nullable()->default(0);
            $table->string('PERFILECONECT')->length(1)->default('B' );
            $table->datetime('DTEMISNFEFORN')->length(7)->nullable();
            $table->string('ESTABTRANSP')->length(1)->nullable();
            $table->string('TRANSPPROPRIA')->length(1)->nullable();
            $table->string('TERMACORD')->length(1)->nullable()->default('N');
            $table->integer('INTERVANALISCRED')->length(10)->nullable()->default(0);
            $table->string('INDCOMERCIALIZACAO')->length(5)->nullable();
            $table->string('INDAQUISICAO')->length(5)->nullable();
            $table->float('MERCHANTID')->length(126)->nullable();
            $table->string('EMAILNOTIFENTREGA')->length(80)->nullable();
            $table->string('IMPAGRUPFIN')->length(1)->nullable();
            $table->integer('TIPLOTACAO')->length(5)->nullable()->default(0);
            $table->integer('UNIDIMPORT')->length(5)->nullable()->default(0);
            $table->integer('CODPARCGRUECONOMICO')->length(10)->nullable()->default(0);
            $table->string('ENQART227')->length(1)->nullable();
            $table->float('LIMCHEQECONECT')->length(126)->nullable();
            $table->string('ORGPUBLNFSE')->length(1)->nullable();
            $table->string('ASSOCIACAODESP')->length(1)->nullable();
            $table->integer('MODELONOTACOMPRA')->length(10)->nullable()->default(0);
            $table->string('ARREDPRIMEIRAPARC')->length(1)->nullable();
            $table->integer('SITCADRF')->length(5)->nullable()->default(0);
            $table->datetime('DHCADRF')->length(7)->nullable();
            $table->string('VLRLIQITEMNFE')->length(1)->nullable();
            $table->string('VLRLIQITEMNFCE')->length(1)->nullable();
            $table->string('CPFPRODRURAL')->length(11)->nullable();
            $table->string('EMAILNFSE')->length(255)->nullable();
            $table->integer('NUFOP')->length(5)->nullable()->default(0);
            $table->string('CNAE')->length(10)->nullable();
            $table->integer('INDCREDNFE')->length(5)->nullable()->default(0);
            $table->integer('INDCREDCTE')->length(5)->nullable()->default(0);
            $table->datetime('DTINIATIV')->length(7)->nullable();
            $table->datetime('DTULTSIT')->length(7)->nullable();
            $table->datetime('DTBAIXA')->length(7)->nullable();
            $table->string('REGAPUR')->length(50)->nullable();
            $table->integer('CODGRUPO')->length(10)->nullable()->default(0);
            $table->string('PARCINTER')->length(1)->nullable();
            $table->integer('INDOPCCP')->length(5)->nullable()->default(0);
            $table->string('TRUNCPARCELA')->length(1)->nullable();
            $table->integer('NUVERSAO')->length(19)->nullable()->default(0);
            $table->integer('CODCONTATOPADCOT')->length(5)->nullable()->default(0);
            $table->string('TIMESTADOCIVIL')->length(2)->nullable()->default('NI');
            $table->string('TIMQUERCOMPRAR')->length(1)->nullable()->default('N');
            $table->string('TIMREFERENCIA02')->length(40)->nullable();
            $table->string('TIMORGAO')->length(10)->nullable();
            $table->string('TIMCOMPRADOR')->length(1)->nullable()->default('N');
            $table->integer('TIMBAIRROCOMPRA')->length(10)->nullable()->default(0);
            $table->datetime('TIMDATACI')->length(7)->nullable();
            $table->string('TIMPROPVENDA')->length(1)->nullable()->default('N');
            $table->string('TIMPAI')->length(50)->nullable();
            $table->string('TIMREFERENCIA01')->length(40)->nullable();
            $table->string('TIMTIPOMORADIA')->length(2)->nullable();
            $table->string('TIMINQUILINO')->length(1)->nullable()->default('N');
            $table->string('TIMTELEFONE02')->length(30)->nullable();
            $table->string('TIMPROPRIETA')->length(1)->nullable()->default('N');
            $table->string('TIMCORRESPBANCARIO')->length(1)->nullable()->default('N');
            $table->string('TIMMAE')->length(50)->nullable();
            $table->string('TIMFAIXASALARIAL')->length(10)->nullable()->default('NI');
            $table->string('TIMCORRETOR')->length(1)->nullable()->default('N');
            $table->string('TIMOUTTELS')->length(400)->nullable();
            $table->string('TIMTELEFONE01')->length(40)->nullable();
            $table->integer('TIMAINVESTIR')->length(12)->nullable()->default(0);
            $table->string('TIMFIADOR')->length(1)->nullable()->default('N');
            $table->string('TIMSENHASITE')->length(8)->nullable()->default('--');
            $table->string('TIMSENHADESC')->length(8)->nullable()->default('--');
            $table->integer('TIMCARTORIO')->length(10)->nullable()->default(0);
            $table->integer('TIMPROFISSAO')->length(10)->nullable()->default(0);
            $table->integer('TIMNACIONALIDAD')->length(10)->nullable()->default(0);
            $table->string('TIMCARTREGIMEBENSV')->length(3)->nullable();
            $table->string('INSCRCNO')->length(12)->nullable();
            $table->string('PARCSUBSTISS')->length(1)->nullable();
            $table->string('EXIGCONTATOENTCAB')->length(1)->nullable();
            $table->string('ENVIADANFEREDESPACHO')->length(1)->nullable();
            $table->string('EXIGENOMEPARC')->length(1)->nullable();
            $table->float('SALDODISPCAC')->length(126)->nullable();
            $table->float('PROVACRESCCAC')->length(126)->nullable();
            $table->string('CONSIDTOTITENSTRIB')->length(1)->nullable();
            $table->string('ATUNUVERSAO')->length(1)->nullable();
            $table->string('DESCONSIDESCBASE')->length(1)->nullable();
            $table->integer('CODIDENTCONS')->length(10)->nullable()->default(0);
            $table->string('UTILIZANUCADPARC')->length(1)->nullable();
            $table->integer('TIPCLIENTESERVCOM')->length(5)->nullable()->default(0);
            $table->string('CHAVEPIX')->length(77)->nullable();
            $table->string('EMAILCTE')->length(255)->nullable();
            $table->string('CONSPARCADRCST')->length(1)->nullable();
            $table->string('DESCONSDESCINSS')->length(1)->nullable();
            $table->string('AD_IDEXTERNO')->length(100)->nullable();
            $table->float('AD_COMISSAO')->length(126)->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('TGFPAR');
    }
}