<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTgfproTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('TGFPRO', function (Blueprint $table) {
            $table->string('DESCRPROD')->length(100);
            $table->string('COMPLDESC')->length(40)->nullable();
            $table->string('CARACTERISTICAS')->length(4000)->nullable();
            $table->string('REFERENCIA')->length(15)->nullable();
            $table->integer('CODGRUPOPROD')->length(10)->default(0);
            $table->string('CODVOL')->length(2);
            $table->string('MARCA')->length(10)->nullable();
            $table->string('LOCALIZACAO')->length(15)->nullable();
            $table->integer('CODIPI')->length(5)->nullable()->default(0);
            $table->integer('CLASSUBTRIB')->length(5)->nullable()->default(0);
            $table->integer('CODFORMPREC')->length(5)->nullable()->default(0);
            $table->float('MARGLUCRO')->length(126)->nullable();
            $table->float('MULTIPVENDA')->length(126)->nullable();
            $table->integer('DECCUSTO')->length(5)->nullable()->default(0);
            $table->integer('DECVLR')->length(5)->nullable()->default(0);
            $table->integer('DECQTD')->length(5)->nullable()->default(0);
            $table->float('COMGER')->length(126)->nullable();
            $table->float('COMVEND')->length(126)->nullable();
            $table->float('DESCMAX')->length(126)->nullable();
            $table->float('PESOBRUTO')->length(126)->default(0);
            $table->float('PESOLIQ')->length(126)->default(0);
            $table->float('MEDAUX')->length(126)->nullable();
            $table->integer('PRAZOVAL')->length(5)->nullable()->default(0);
            $table->float('AGRUPMIN')->length(126)->nullable();
            $table->integer('QTDEMB')->length(5)->nullable()->default(0);
            $table->string('ALERTAESTMIN')->length(1)->default('S' );
            $table->string('PROMOCAO')->length(1)->default('N' );
            $table->string('TEMICMS')->length(1)->default('N' );
            $table->string('TEMISS')->length(1)->default('N' );
            $table->string('TEMIPIVENDA')->length(1)->default('N' );
            $table->string('TEMIPICOMPRA')->length(1)->default('N' );
            $table->string('TEMIRF')->length(1)->default('N' );
            $table->float('PERCIRF')->length(126)->nullable();
            $table->string('TEMINSS')->length(1)->default('N' );
            $table->float('PERCINSS')->length(126)->default(0);
            $table->float('REDBASEINSS')->length(126)->default(0);
            $table->string('USOPROD')->length(1)->nullable()->default('V');
            $table->string('ORIGPROD')->length(1)->nullable()->default('0');
            $table->string('TIPSUBST')->length(1)->nullable()->default('N');
            $table->float('CODICMSFAST')->length(126)->nullable();
            $table->string('TIPLANCNOTA')->length(1)->nullable()->default('A');
            $table->string('TIPCONTEST')->length(1)->nullable()->default('N');
            $table->integer('CODTAB')->length(5)->nullable()->default(0);
            $table->integer('CODCTACTB')->length(10)->nullable()->default(0);
            $table->text('IMAGEM')->length(4000)->nullable();
            $table->string('ATIVO')->length(1)->default('S' );
            $table->float('ESTMAX')->length(126)->nullable();
            $table->float('ESTMIN')->length(126)->nullable();
            $table->string('APRESDETALHE')->length(1)->default('N' );
            $table->string('SELECIONADO')->length(1)->nullable();
            $table->string('TITCONTEST')->length(10)->nullable();
            $table->string('LISCONTEST')->length(4000)->nullable();
            $table->integer('CODMOEDA')->length(5)->default(0);
            $table->integer('GRUPOICMS')->length(10)->nullable()->default(0);
            $table->float('PERCAUMENTCUSTO')->length(126)->nullable();
            $table->string('LOCAL')->length(1)->default('N' );
            $table->datetime('DTALTER')->length(7);
            $table->string('USALOCAL')->length(1)->default('N' );
            $table->string('HOMEPAGE')->length(255)->nullable();
            $table->integer('CODCTACTB2')->length(10)->nullable()->default(0);
            $table->integer('CODCTACTB3')->length(10)->nullable()->default(0);
            $table->datetime('TEMPOSERV')->length(7)->nullable();
            $table->string('ENDIMAGEM')->length(200)->nullable();
            $table->integer('CODUSU')->length(5)->default(0);
            $table->integer('CODPARCFORN')->length(10)->nullable()->default(0);
            $table->string('CODVOLCOMPRA')->length(2)->nullable()->default('0');
            $table->string('CODPRODROI')->length(2)->nullable();
            $table->string('GRUPODESCPROD')->length(15)->nullable();
            $table->string('REFFORN')->length(30)->nullable();
            $table->string('HRDOBRADA')->length(1)->default('N' );
            $table->string('ICMSGERENCIA')->length(1)->default('N' );
            $table->integer('CODNAT')->length(10)->default(0);
            $table->integer('CODCENCUS')->length(10)->default(0);
            $table->integer('CODPROJ')->length(10)->default(0);
            $table->float('M3')->length(126)->nullable();
            $table->string('TEMCIAP')->length(1)->default('N' );
            $table->string('IMPLAUDOLOTE')->length(1)->default('N' );
            $table->integer('CODGAR')->length(10)->nullable()->default(0);
            $table->string('DIMENSOES')->length(1)->default('N' );
            $table->float('PERCQUEBRATEC')->length(126)->nullable();
            $table->integer('CODCTACTB4')->length(10)->nullable()->default(0);
            $table->integer('CODFILTRO')->length(5)->nullable()->default(0);
            $table->integer('CODGENERO')->length(10)->nullable()->default(0);
            $table->integer('CODLST')->length(10)->nullable()->default(0);
            $table->string('PADRAO')->length(1)->default('S' );
            $table->string('ENDMODROTULO')->length(255)->nullable();
            $table->string('NATUREZAOPERDES')->length(2)->nullable();
            $table->integer('CNAE')->length(10)->nullable()->default(0);
            $table->string('SOLCOMPRA')->length(1)->default('N' );
            $table->string('CONFERE')->length(1)->default('S' );
            $table->string('REMETER')->length(1)->default('N' );
            $table->string('MOTIVOINCEXC')->length(1)->nullable();
            $table->integer('ARREDPRECO')->length(10)->nullable()->default(0);
            $table->string('TEMCOMISSAO')->length(1)->default('S' );
            $table->string('COMPONOBRIG')->length(1)->nullable();
            $table->string('FATTOTAL')->length(1)->nullable();
            $table->string('NOMETAB')->length(32)->nullable();
            $table->string('AP1RCTEGO')->length(1)->default('N' );
            $table->string('CALCULOGIRO')->length(1)->default('E' );
            $table->float('REDBASEIRF')->length(126)->nullable();
            $table->float('ALTURA')->length(126)->nullable();
            $table->float('LARGURA')->length(126)->nullable();
            $table->float('ESPESSURA')->length(126)->nullable();
            $table->string('UNIDADE')->length(2)->default('MM' );
            $table->integer('CODFORMAPONTA')->length(5)->nullable()->default(0);
            $table->integer('CODCOS')->length(5)->nullable()->default(0);
            $table->string('CONFCEGAPESO')->length(1)->default('N' );
            $table->integer('ORDCALCCUSTPROD')->length(5)->nullable()->default(0);
            $table->string('REGRAWMS')->length(1)->default('O' );
            $table->string('GRUPOPIS')->length(30)->default('TODOS' );
            $table->string('GRUPOCOFINS')->length(30)->default('TODOS' );
            $table->string('GRUPOCSSL')->length(30)->default('TODOS' );
            $table->integer('CSTIPIENT')->length(5)->nullable()->default(0);
            $table->integer('CSTIPISAI')->length(5)->nullable()->default(0);
            $table->string('STATUSINCEXC')->length(1)->nullable();
            $table->string('UTILIZAWMS')->length(1)->default('N' );
            $table->string('BALANCA')->length(1)->default('N' );
            $table->integer('CODPAIS')->length(5)->nullable()->default(0);
            $table->string('RENDIMENTO')->length(50)->nullable();
            $table->string('OBSETIQUETA')->length(120)->nullable();
            $table->integer('CODANP')->length(10)->nullable()->default(0);
            $table->string('CODAUTCODIF')->length(21)->nullable();
            $table->integer('CODPRODAGRUPAPT')->length(10)->nullable()->default(0);
            $table->integer('CODPRODAGRUPAPTENC')->length(10)->nullable()->default(0);
            $table->string('CULTURA')->length(80)->nullable();
            $table->string('CIENTIFICO')->length(80)->nullable();
            $table->integer('CLASSEAGT')->length(10)->nullable()->default(0);
            $table->integer('GRUPOQUIMICO')->length(10)->nullable()->default(0);
            $table->integer('CLASSETOX')->length(10)->nullable()->default(0);
            $table->integer('PRINCATIVO')->length(10)->nullable()->default(0);
            $table->string('FORMULACAO')->length(180)->nullable();
            $table->string('CONCENTRACAO')->length(30)->nullable();
            $table->string('MODOAPLIC')->length(240)->nullable();
            $table->string('EPOCAAPLIC')->length(120)->nullable();
            $table->string('MANEJOINT')->length(120)->nullable();
            $table->float('DOSAGEM')->length(126)->nullable();
            $table->string('VOLDOSAGEM')->length(2)->nullable();
            $table->float('DOSAGEMPOR')->length(126)->nullable();
            $table->string('VOLDOSAGEMPOR')->length(2)->nullable();
            $table->string('RENDIMENTOPR')->length(15)->nullable();
            $table->string('RECEITUARIO')->length(1)->nullable()->default('N');
            $table->string('EXIGEBENEFIC')->length(1)->nullable()->default('N');
            $table->string('TIPOCLASSEAGT')->length(1)->nullable();
            $table->string('TIPOGRUPOQUIMICO')->length(1)->nullable();
            $table->string('TIPOPRINCATIVO')->length(1)->nullable();
            $table->string('TIPOCLASSETOX')->length(1)->nullable();
            $table->integer('GRUPOTRANSG')->length(10)->nullable()->default(0);
            $table->string('GERAPLAPROD')->length(1)->default('N' );
            $table->integer('APLICACAO')->length(10)->nullable()->default(0);
            $table->integer('INTERVALO')->length(10)->nullable()->default(0);
            $table->integer('CARENCIA')->length(10)->nullable()->default(0);
            $table->float('RENDIMENTOHA')->length(126)->nullable();
            $table->integer('PRODUTONFE')->length(5)->default(0);
            $table->integer('TIPGTINNFE')->length(5)->default(2);
            $table->string('NCM')->length(10)->nullable();
            $table->string('CODVOLPLAN')->length(2)->nullable();
            $table->float('DESCMAXFLEX')->length(126)->nullable();
            $table->float('ACRESCMAX')->length(126)->nullable();
            $table->string('FLEX')->length(1)->default('S' );
            $table->integer('NUMITEMREA')->length(10)->nullable()->default(0);
            $table->string('IMPRIMIR')->length(1)->default('0' );
            $table->string('CONFIRMAIMP')->length(1)->default('N' );
            $table->string('APURAPRODEPE')->length(2)->nullable();
            $table->string('INDESPPRODEPE')->length(2)->nullable();
            $table->integer('QTDNFLAUDOSINT')->length(10)->default(0);
            $table->string('CODTRIBMUNISS')->length(20)->nullable();
            $table->string('TIPCONTESTWMS')->length(1)->default('N' );
            $table->string('LISTALPM')->length(1)->default('N' );
            $table->string('ONEROSO')->length(1)->default('N' );
            $table->string('REFMERCMED')->length(1)->default('N' );
            $table->string('TERMOLABIL')->length(1)->default('N' );
            $table->float('TEMPMINIMA')->length(126)->nullable();
            $table->float('TEMPMAXIMA')->length(126)->nullable();
            $table->string('CONTROLADO')->length(1)->default('N' );
            $table->string('IDENPORTARIA')->length(30)->nullable();
            $table->string('IDENOTC')->length(30)->nullable();
            $table->string('IDENCORRELATO')->length(1)->default('N' );
            $table->string('IDENCOSME')->length(1)->default('N' );
            $table->string('PRODFALTA')->length(1)->default('N' );
            $table->integer('CODFAB')->length(10)->nullable()->default(0);
            $table->integer('STATUSMED')->length(10)->default(0);
            $table->integer('CODCPR')->length(10)->nullable()->default(0);
            $table->integer('SEQSPR')->length(5)->nullable()->default(0);
            $table->integer('SEQSCA')->length(5)->nullable()->default(0);
            $table->integer('SEQSTE')->length(5)->nullable()->default(0);
            $table->integer('CODCAT')->length(10)->nullable()->default(0);
            $table->integer('CODTER')->length(10)->nullable()->default(0);
            $table->integer('CODPAT')->length(10)->nullable()->default(0);
            $table->float('MVAAJUSTADO')->length(126)->default(0);
            $table->string('INFPUREZA')->length(1)->default('N' );
            $table->string('FABRICANTE')->length(80)->nullable();
            $table->string('USASTATUSLOTE')->length(1)->default('N' );
            $table->integer('TAMLOTE')->length(5)->nullable()->default(0);
            $table->integer('TAMSERIE')->length(5)->nullable()->default(0);
            $table->string('UNIDMINARMAZ')->length(2)->nullable();
            $table->string('ORIGEMFAT')->length(1)->default('E' );
            $table->string('USACODBARRASQTD')->length(1)->default('N' );
            $table->string('MD5PAF')->length(32)->nullable();
            $table->string('VALCAPM3')->length(1)->default('N' );
            $table->string('QTDPECAFRAC')->length(1)->default('N' );
            $table->string('UTILORDCORTE')->length(1)->default('N' );
            $table->integer('CODPRODPERDA')->length(10)->nullable()->default(0);
            $table->string('DESCRUTILBEM')->length(4000)->nullable();
            $table->string('IMPORDEMCORTE')->length(1)->default('N' );
            $table->float('PERCTROCA')->length(126)->default(0);
            $table->integer('CORFONTCONSPRECO')->length(10)->nullable()->default(0);
            $table->integer('CORFUNDOCONSPRECO')->length(10)->nullable()->default(0);
            $table->string('CODVOLRES')->length(2)->nullable();
            $table->integer('CODAREASEP')->length(10)->nullable()->default(0);
            $table->integer('IDENTIMOB')->length(5)->nullable()->default(0);
            $table->integer('UTILIMOB')->length(5)->nullable()->default(0);
            $table->string('TEMCREDPISCOFINSDEPR')->length(1)->default('N' );
            $table->integer('CODPRODINNATURA')->length(10)->nullable()->default(0);
            $table->string('UTILSMARTCARD')->length(1)->default('N' );
            $table->string('RECUPAVARIA')->length(1)->default('N' );
            $table->float('CONVERVOL')->length(126)->nullable();
            $table->integer('LASTRO')->length(10)->nullable()->default(0);
            $table->integer('CAMADAS')->length(10)->nullable()->default(0);
            $table->float('ORDEMMEDIDA')->length(126)->nullable();
            $table->float('ALIQICMSINTEFD')->length(126)->nullable();
            $table->string('CODREGMAPA')->length(20)->nullable();
            $table->string('APRESFORM')->length(1)->default('S' );
            $table->string('CODBARCOMP')->length(1)->default('N' );
            $table->string('TEMMEDICAO')->length(1)->default('N' );
            $table->integer('CODFILTROREQ')->length(5)->nullable()->default(0);
            $table->string('NATBCPISCOFINS')->length(1)->default('D' );
            $table->string('CONTARPORPESO')->length(1)->default('N' );
            $table->integer('CODLOCALPADRAO')->length(10)->nullable()->default(0);
            $table->string('PERMCOMPPROD')->length(1)->default('S' );
            $table->integer('CODEXNCM')->length(5)->default(0);
            $table->integer('QTDCST')->length(10)->default(0);
            $table->integer('DIASCST')->length(10)->default(0);
            $table->integer('PERCTOLVARCST')->length(10)->default(100);
            $table->float('QTDPEDPEND')->length(126)->nullable();
            $table->integer('LEADTIME')->length(10)->nullable()->default(0);
            $table->integer('DIASEXPEDICAO')->length(10)->nullable()->default(0);
            $table->string('DTVALDIF')->length(1)->default('X' );
            $table->integer('SHELFLIFEMIN')->length(10)->nullable()->default(0);
            $table->integer('SHELFLIFE')->length(10)->nullable()->default(0);
            $table->string('CODBARBALANCA')->length(1)->default('N' );
            $table->string('VALCBGLOBAL')->length(1)->default('N' );
            $table->string('USAPONTOS')->length(1)->default('N' );
            $table->integer('CODRFA')->length(10)->nullable()->default(0);
            $table->integer('PERCROYALTY')->length(18)->nullable()->default(0);
            $table->string('INTEGRAECONECT')->length(1)->default('N' );
            $table->string('ENQREINTEGRA')->length(1)->default('N' );
            $table->float('PERCCMTNAC')->length(126)->default(0);
            $table->float('PERCCMTIMP')->length(126)->default(0);
            $table->string('CODATIVREINTEGRA')->length(8)->nullable();
            $table->string('NOTIFCONF')->length(500)->nullable();
            $table->string('USASERIEFAB')->length(1)->nullable();
            $table->string('TIPSERNFE')->length(1)->nullable();
            $table->string('VENCOMPINDIV')->length(1)->nullable();
            $table->string('EXCLUIRCONF')->length(1)->nullable();
            $table->string('PRODUZAUT')->length(1)->default('N' );
            $table->string('USAIMPAGRUPMIN')->length(1)->default('S' );
            $table->string('RASTRESTOQUE')->length(1)->default('N' );
            $table->string('IMPETIQCONF')->length(1)->default('S' );
            $table->float('VLRCOMERC')->length(126)->nullable();
            $table->float('VLRPARCIMPEXT')->length(126)->nullable();
            $table->string('CODFCI')->length(36)->nullable();
            $table->string('SERVPARAINDUST')->length(1)->default('N' );
            $table->string('DESCRPRODNFE')->length(100)->nullable();
            $table->string('CAT1799SPRES')->length(1)->default('N' );
            $table->float('ALIQNAC')->length(126)->nullable();
            $table->float('ALIQIMP')->length(126)->nullable();
            $table->float('ESTSEGQTD')->length(126)->default(0);
            $table->integer('ESTSEGDIAS')->length(5)->nullable()->default(0);
            $table->datetime('DTALTERESQ')->length(7)->nullable();
            $table->integer('LOTECOMPRAS')->length(5)->nullable()->default(0);
            $table->float('ESTMAXQTD')->length(126)->default(0);
            $table->integer('ESTMAXDIAS')->length(5)->nullable()->default(0);
            $table->datetime('DTALTEREMQ')->length(7)->nullable();
            $table->float('DESVIOMAX')->length(126)->default(0);
            $table->float('ARREDAGRUP')->length(126)->default(0.5 );
            $table->string('APLICASAZO')->length(1)->default('S' );
            $table->float('LOTECOMPMINIMO')->length(126)->default(0);
            $table->float('AGRUPCOMPMINIMO')->length(126)->default(0);
            $table->string('USASERIESEPWMS')->length(1)->default('N' );
            $table->string('GERACUSTCOMPSEG')->length(1)->default('N' );
            $table->integer('TOPFATURCON')->length(5)->nullable()->default(0);
            $table->string('SERFATURCON')->length(3)->nullable();
            $table->integer('CODGPROD')->length(10)->nullable()->default(0);
            $table->string('EXIGELASTROCAMADAS')->length(1)->nullable()->default('S');
            $table->string('FIXOAGENDA')->length(1)->default('S' );
            $table->integer('CODPARCCONSIG')->length(10)->nullable()->default(0);
            $table->string('USALOTEDTVAL')->length(1)->nullable();
            $table->string('USALOTEDTFAB')->length(1)->nullable();
            $table->string('EXIBCOMPEXPKIT')->length(1)->default('T' );
            $table->integer('TIPORECEITAMOD21')->length(5)->nullable()->default(0);
            $table->integer('CODPRODSUBST')->length(10)->nullable()->default(0);
            $table->datetime('DTSUBST')->length(7)->nullable();
            $table->integer('CODCOMP')->length(10)->nullable()->default(0);
            $table->integer('NATEFDCONTM410M810')->length(5)->nullable()->default(0);
            $table->float('PERCTOLPESOMAIOR')->length(126)->nullable();
            $table->float('PERCTOLPESOMENOR')->length(126)->nullable();
            $table->string('CODVOLPESOVAR')->length(2)->nullable();
            $table->string('USACONTPESOVAR')->length(1)->nullable();
            $table->float('PERCTOLPESOMAIORSEP')->length(126)->nullable();
            $table->float('PERCTOLPESOMENORSEP')->length(126)->nullable();
            $table->float('PCT_BF')->length(126)->nullable();
            $table->integer('PRZ_BF')->length(5)->nullable()->default(0);
            $table->string('CONTROLMEDIC')->length(1)->nullable();
            $table->integer('DECVLRENT')->length(5)->nullable()->default(0);
            $table->float('PERCCMTFED')->length(126)->default(0);
            $table->float('PERCCMTEST')->length(126)->default(0);
            $table->float('PERCCMTMUN')->length(126)->default(0);
            $table->integer('CODENQIPIENT')->length(5)->nullable()->default(0);
            $table->integer('CODENQIPISAI')->length(5)->nullable()->default(0);
            $table->string('DESCVENCONSUL')->length(1)->nullable()->default('N');
            $table->integer('GRUPOICMS2')->length(10)->nullable()->default(0);
            $table->float('MVAPADRAO')->length(126)->nullable();
            $table->float('ALIQGERAL')->length(126)->nullable();
            $table->integer('CODPRODSUBKIT')->length(10)->nullable()->default(0);
            $table->integer('CODCONFKIT')->length(10)->nullable()->default(0);
            $table->string('TIPOKIT')->length(1)->nullable();
            $table->integer('CODESPECST')->length(10)->nullable()->default(0);
            $table->string('VISIVELAPPOS')->length(1)->nullable();
            $table->string('UTILIZAENDFLUT')->length(1)->nullable()->default('N');
            $table->integer('MAXMULTECONECT')->length(5)->nullable()->default(0);
            $table->integer('CODVTP')->length(10)->nullable()->default(0);
            $table->integer('QTDIDENTIF')->length(10)->nullable()->default(0);
            $table->string('TIPOIDENTIF')->length(50)->nullable();
            $table->integer('MODETIQSEPWMS')->length(5)->nullable()->default(0);
            $table->string('IMPETIQSEPWMS')->length(1)->nullable();
            $table->string('NROPROCESSO')->length(30)->nullable();
            $table->integer('TIPOSN')->length(5)->nullable()->default(0);
            $table->string('ARMAZELOTE')->length(1)->default('N' );
            $table->string('TEMRASTROLOTE')->length(1)->default('N' );
            $table->string('CODANVISA')->length(13)->nullable();
            $table->string('DESCRANP')->length(95)->nullable();
            $table->float('PERCMISTGLP')->length(126)->nullable();
            $table->integer('CODSERVTELECOM')->length(5)->nullable()->default(0);
            $table->string('TIPOCONTAGEM')->length(1)->default('D' );
            $table->integer('CODMARCA')->length(10)->nullable()->default(0);
            $table->float('PERCMISTGNN')->length(126)->nullable();
            $table->float('PERCMISTGNI')->length(126)->nullable();
            $table->float('VLRPARTIDAGLP')->length(126)->nullable();
            $table->integer('CODCTACTBEFD')->length(10)->nullable()->default(0);
            $table->string('CODCPRB')->length(8)->nullable();
            $table->string('COMERCIALIZACAOAGRI')->length(1)->nullable();
            $table->integer('OBRACONSTCIVIL')->length(5)->nullable()->default(0);
            $table->integer('CLASSIFCESSAOOBRA')->length(10)->nullable()->default(0);
            $table->string('TIPOINSSESPECIAL')->length(1)->nullable();
            $table->float('PERCINSSESPECIAL')->length(126)->nullable();
            $table->string('CALCDIFAL')->length(1)->default('N' );
            $table->string('INDESCALA')->length(1)->nullable();
            $table->string('CNPJFABRICANTE')->length(14)->nullable();
            $table->string('CODBENEFNAUF')->length(10)->nullable();
            $table->string('CODAGREGACAO')->length(20)->nullable();
            $table->float('QTDAGRUPAMENTOMTZ')->length(126)->nullable();
            $table->integer('CODIDCNAE')->length(10)->nullable()->default(0);
            $table->integer('CODFILTROCTA')->length(5)->nullable()->default(0);
            $table->string('FORCAEXPECONECT')->length(1)->nullable();
            $table->string('REGISTRARPESO')->length(2)->nullable();
            $table->integer('DESVIOMAXTOLCONFSEP')->length(5)->nullable()->default(0);
            $table->integer('DESVIOMINTOLCONFSEP')->length(5)->nullable()->default(0);
            $table->string('SERVPRESTTER')->length(1)->nullable();
            $table->string('FRAGMENTALOTE')->length(1)->nullable()->default('N');
            $table->float('PERCREDBASEICMSEFET')->length(126)->nullable();
            $table->integer('NUVERSAOIMG')->length(19)->nullable()->default(0);
            $table->integer('INTEGRAFOX')->length(10)->nullable()->default(0);
            $table->integer('NUVERSAO')->length(19)->nullable()->default(0);
            $table->string('MOTISENCAOANVISA')->length(255)->nullable();
            $table->string('CODNBS')->length(9)->nullable();
            $table->string('CONSPRODCAT42')->length(1)->nullable();
            $table->string('TIPOITEMSPED')->length(2)->nullable();
            $table->float('INCPESOBRUTO')->length(126)->nullable();
            $table->float('INCPESOLIQUIDO')->length(126)->nullable();
            $table->integer('NURFE')->length(10)->nullable()->default(0);
            $table->float('MVAORIGINALDRCST')->length(126)->nullable();
            $table->float('TAMANHOMEDIOPECA')->length(126)->nullable();
            $table->integer('IDGRADE')->length(10)->nullable()->default(0);
            $table->float('PERCENTSEPPUL')->length(126)->nullable();
            $table->string('ATUNUVERSAO')->length(1)->nullable();
            $table->text('GRADEPADRAO')->length(4000)->nullable();
            $table->float('ALIQFETHAB')->length(126)->nullable();
            $table->string('CODVOLFETHAB')->length(2)->nullable();
            $table->string('OBTSTANTMEDENT')->length(1)->nullable();
            $table->string('DESCPRODDRCST')->length(1)->nullable();
            $table->string('PARTICIPAADRCST')->length(1)->nullable();
            $table->float('MVAORIGINALADRCST')->length(126)->nullable();
            $table->float('ALIQFECOP')->length(126)->nullable();
            $table->string('PRODSUJFECOP')->length(1)->nullable();
            $table->string('DESDESCCALCPIS')->length(1)->nullable();
            $table->float('ALIQINTERNACAT42')->length(126)->nullable();
            $table->string('CONESTORIGPROD')->length(1)->nullable();
            $table->string('GERIMPNRETREINFAQ')->length(1)->nullable();
            $table->string('PRODALIADRCST')->length(1)->nullable();
            $table->integer('TIPUTILCOM')->length(5)->nullable()->default(0);
            $table->string('PRODINTERNO')->length(1)->nullable();
            $table->string('CALCFUSTPRO')->length(1)->nullable();
            $table->string('CALCFUNTTELPRO')->length(1)->nullable();
            $table->string('CODBARDIFGTIN')->length(30)->nullable();
            $table->string('CODBARTRIBDIFGTIN')->length(30)->nullable();
            $table->string('WMSPRODRASTSERMED')->length(1)->nullable();
            $table->string('STATUSNCM')->length(1)->nullable();
            $table->string('BLOQVENDAFRAC')->length(1)->nullable();
            $table->string('AD_EXTERNO_CODGRUPOPROD')->length(100)->nullable();
            $table->string('AD_IDEXTERNO')->length(100)->nullable();
            $table->integer('AD_CODCENCUSCOM')->length(10)->default(0);
            $table->integer('AD_CODNATCOM')->length(10)->default(0);
            $table->integer('AD_CODEMP')->length(5)->nullable()->default(0);
            $table->integer('TPIRRFEXT')->length(5)->nullable()->default(0);
            $table->integer('CODNATREND')->length(10)->nullable()->default(0);
            $table->string('INDTIPREFBCICMSST')->length(1)->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('TGFPRO');
    }
}