<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tgftit extends Model
{
    protected $fillable = [
        'DESCRTIPTIT',
        'ESPDOC',
        'CARENCIA',
        'FISCAL',
        'EXPTES',
        'EXPGRS',
        'CARTAOTAXA',
        'CARTAODESC',
        'VALIDAQTDMAXTITVENCIDOS',
        'EXIGBAIXAACERTO',
        'TRANSFDIF',
        'INDTIT',
        'TRANSFPEND',
        'TRANSFBAIX',
        'PERCJUROS',
        'PERCMULTA',
        'CODMOEDA',
        'EXIBBAIX',
        'CODCTACTB',
        'CODCTACTB2',
        'CODCTACTB3',
        'BAIXACERTO',
        'INFCMC7',
        'GRUPOLIMCRED',
        'FASTUSA',
        'IMAGEM',
        'PERCCUSVAR',
        'VLRCUSVAR',
        'FASTBAIXA',
        'PRAZO',
        'CODGRUPOTIPTIT',
        'IMPBOLRENEG',
        'SUBTIPOVENDA',
        'CONFERENCIA',
        'ATIVO',
        'CODPARCTEF',
        'IMPCOMPROVANTE',
        'CODRECGNRE',
        'CODDETRECGNRE',
        'CODPRODGNRE',
        'TPAGNFCE',
        'AJUSTAVP',
        'UTILIZAPOS',
        'NROPARCELAS',
        'INTEGRAECONECT',
        'CODFINALIZADORA',
        'GRUPOFINALIZADORA',
        'CODBANDEIRAECONECT',
        'CONVENIOECONECT',
        'DIAVENC',
        'TIPVENC',
        'OPERACAOCTF',
        'QTDPARCELCTF',
        'RECEBANTAPROV',
        'ARREDPRIMEIRAPARC',
        'TRUNCPARCELA',
        'TIMUSADOLOCACAO',
        'TIPDOCRURAL',
        'PROIBIMPBOL',
        'ALTERASIMULTPV',
        'DESCRTPAGNFCE',
        'INDRECEFDCONT',
        'INFCOMPLEFDCONT',
        'CONSDIASUTEIS',
        'CREDENCIADORACFE',
        'UTILIZAPIXSITEF',
    ];
}