<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTGMMETTable extends Migration
{
	public function up()
	{
		Schema::create('TGMMET', function (Blueprint $table) {
			$table->integer('CODVEND');
			$table->integer('NUFIN');
			$table->integer('CODTIPTIT');
			$table->integer('CODPROD');
			$table->integer('CODCTACTB');
			$table->integer('NUNOTA');
			$table->integer('NUNOTA');
			$table->integer('CODNAT');
			$table->integer('CODEMP');
			$table->integer('CODPARC');
			$table->integer('NUNOTA');
			$table->integer('CODEMP');
			$table->integer('CODCENCUS');
			$table->integer('CODCTABCOINT');
			$table->integer('CODBCO');
			$table->integer('NUTAB');
			$table->integer('CODCFO');
			$table->date('DTREF');
			$table->integer('SEQUENCIA');
			$table->integer('CODPROD');
			$table->integer('SEQUENCIA');
			$table->integer('CODEMP');
			$table->integer('NUNOTAORIG');
			$table->integer('CODLOCAL');
			$table->integer('CODPROD');
			$table->integer('SEQUENCIAORIG');
			$table->string('CONTROLE')->length(19)->default(' ' );
			$table->integer('CODGRUPOPROD');
			$table->integer('CODPARC');
			$table->integer('CODLOCAL');
			$table->string('TIPO')->length(1)->default('P' );
			$table->integer('CODPROJ');
			$table->integer('CODCENCUS');
			$table->integer('CODNAT');
			$table->integer('CODREG');
			$table->integer('CODGER');
			$table->integer('CODVEND');
			$table->integer('CODPARC');
			$table->integer('CODUF');
			$table->integer('CODCID');
			$table->integer('CODPAIS');
			$table->integer('CODTIPPARC');
			$table->string('CONTROLE')->length(19)->default(' ' );
			$table->string('MARCA')->length(10)->default(' ' );
			$table->integer('DIA');
			$table->integer('CODGRUPONAT');
			$table->float('QTDPREV')->nullable();
			$table->float('PREVREC')->nullable();
			$table->float('PREVDESP')->nullable();
			$table->float('QTDREAL')->nullable();
			$table->float('REALREC')->nullable();
			$table->float('REALDESP')->nullable();
			$table->float('PERCENTUAL')->nullable();
			$table->float('SUPLEMENTODESP')->nullable();
			$table->float('ANTECIPDESP')->nullable();
			$table->float('TRANSFDESP')->nullable();
			$table->float('TRANSFSALDODESP')->nullable();
			$table->float('REDUCAODESP')->nullable();
			$table->float('COMPROMISSODESP')->nullable();
			$table->string('ANALITICO')->length(1)->default('S' );
			$table->string('TIPOMSG')->length(1)->default('Z' );
			$table->float('PERCAVISO')->nullable();
			$table->integer('SEMANAMES')->nullable();
			$table->float('TOTALAUTINV');
			$table->string('CODVOL')->length(2)->nullable();
			$table->date('DHALTER')->nullable();
			$table->float('ACRESCMAX')->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->string('APELIDO')->length(15);
			$table->string('ATIVO')->length(1)->default('S' );
			$table->string('ATUACOMPRADOR')->length(1)->nullable()->default('N');
			$table->integer('CODCARGAHOR');
			$table->integer('CODCENCUSPAD');
			$table->integer('CODEMP')->nullable();
			$table->integer('CODFORM');
			$table->integer('CODFORMFLEX')->nullable();
			$table->integer('CODFUNC')->nullable();
			$table->integer('CODGER');
			$table->integer('CODPARC');
			$table->integer('CODREG');
			$table->integer('CODUSU')->nullable();
			$table->string('COMCM')->length(1)->default('N' );
			$table->float('COMGER')->nullable();
			$table->float('COMISSAO2')->nullable();
			$table->float('COMVENDA')->nullable();
			$table->float('DESCMAX')->nullable();
			$table->integer('DIACOM')->nullable();
			$table->date('DTALTER');
			$table->string('EMAIL')->length(80)->nullable();
			$table->string('GRUPODESCVEND')->length(15)->nullable();
			$table->string('GRUPORETENCAO')->length(15)->nullable();
			$table->integer('NUVERSAO')->nullable();
			$table->float('PARTICMETA')->nullable();
			$table->float('PERCCUSVAR')->nullable();
			$table->float('PERCTROCA');
			$table->float('PROVACRESC');
			$table->float('PROVACRESCCAC')->nullable();
			$table->string('RECHREXTRA')->length(1)->default('S' );
			$table->float('SALDODISP');
			$table->float('SALDODISPCAC')->nullable();
			$table->integer('SENHA')->nullable();
			$table->string('TIPCALC')->length(1)->default('N' );
			$table->string('TIPFECHCOM')->length(1)->default('N' );
			$table->string('TIPVALOR')->length(1)->default('U' );
			$table->string('TIPVEND')->length(1)->nullable();
			$table->float('VLRHORA')->nullable();
			$table->integer('CODEMP');
			$table->integer('NUMNOTA');
			$table->string('SERIENOTA')->length(3)->nullable();
			$table->date('DTNEG');
			$table->string('DESDOBRAMENTO')->length(2)->nullable();
			$table->date('DHMOV');
			$table->date('DTVENCINIC')->nullable();
			$table->date('DTVENC')->nullable();
			$table->date('DHBAIXA')->nullable();
			$table->date('DTCONTAB')->nullable();
			$table->date('DTCONTABBAIXA')->nullable();
			$table->integer('CODPARC');
			$table->integer('CODTIPOPER');
			$table->date('DHTIPOPER')->default(TO_DATE('01/01/1998', 'DD/MM/YYYY') );
			$table->integer('CODBCO');
			$table->integer('CODCTABCOINT')->nullable();
			$table->integer('CODNAT');
			$table->integer('CODCENCUS');
			$table->integer('CODPROJ')->nullable();
			$table->integer('CODVEND');
			$table->integer('CODMOEDA');
			$table->integer('CODTIPTIT');
			$table->integer('NUMDUPL')->nullable();
			$table->string('DESDOBDUPL')->length(2)->nullable();
			$table->string('NOSSONUM')->length(12)->nullable();
			$table->string('HISTORICO')->length(255)->nullable();
			$table->float('VLRDESDOB');
			$table->float('VLRVENDOR');
			$table->float('VLRIRF');
			$table->float('VLRISS');
			$table->float('VLRCHEQUE')->nullable();
			$table->float('DESPCART');
			$table->string('ISSRETIDO')->length(1)->default('N' );
			$table->float('VLRDESC');
			$table->float('VLRMULTA');
			$table->float('VLRINSS');
			$table->string('TIPMULTA')->length(1)->nullable()->default('1');
			$table->float('VLRJURO');
			$table->string('TIPJURO')->length(1)->nullable()->default('1');
			$table->float('BASEICMS');
			$table->float('ALIQICMS');
			$table->integer('CODEMPBAIXA')->nullable();
			$table->integer('CODTIPOPERBAIXA');
			$table->date('DHTIPOPERBAIXA')->default(TO_DATE('01/01/1998', 'DD/MM/YYYY') );
			$table->float('VLRBAIXA');
			$table->integer('NUMREMESSA')->nullable();
			$table->string('AUTORIZADO')->length(1)->default('N' );
			$table->integer('RECDESP');
			$table->string('PROVISAO')->length(1)->default('N' );
			$table->string('ORIGEM')->length(1)->default('F' );
			$table->string('TIPMARCCHEQ')->length(1)->default('A' );
			$table->integer('NUNOTA')->nullable();
			$table->integer('NUBCO')->nullable();
			$table->integer('NUDEV')->nullable();
			$table->integer('NURENEG')->nullable();
			$table->integer('CARTA')->nullable();
			$table->string('RATEADO')->length(1)->default('N' );
			$table->date('DTENTSAI')->nullable();
			$table->integer('CODUSUBAIXA')->nullable();
			$table->integer('VLRPROV');
			$table->string('IRFRETIDO')->length(1)->nullable()->default('N');
			$table->string('INSSRETIDO')->length(1)->default('N' );
			$table->float('CARTAODESC')->nullable();
			$table->date('DTALTER');
			$table->integer('NUMCONTRATO');
			$table->integer('ORDEMCARGA');
			$table->integer('CODVEICULO');
			$table->string('CODBARRA')->length(50)->nullable();
			$table->integer('CODUSU');
			$table->integer('SEQUENCIA')->nullable();
			$table->float('VLRVARCAMBIAL')->nullable();
			$table->string('CODIGOBARRA')->length(55)->nullable();
			$table->string('LINHADIGITAVEL')->length(57)->nullable();
			$table->float('VLRDESCEMBUT')->nullable();
			$table->float('VLRJUROEMBUT')->nullable();
			$table->float('VLRMULTAEMBUT')->nullable();
			$table->float('VLRMOEDA')->nullable();
			$table->float('VLRMOEDABAIXA')->nullable();
			$table->integer('NUCOMPENS')->nullable();
			$table->integer('CODCFO')->nullable();
			$table->float('VLRMULTANEGOC')->nullable();
			$table->float('VLRJURONEGOC')->nullable();
			$table->float('VLRMULTALIB')->nullable();
			$table->float('VLRJUROLIB')->nullable();
			$table->date('DTBAIXAPREV')->nullable();
			$table->integer('NUMOS')->nullable();
			$table->string('NATUREZAOPERDES')->length(2)->nullable();
			$table->string('SERIENFDES')->length(4)->nullable();
			$table->string('MODELONFDES')->length(2)->nullable();
			$table->integer('CODFUNC')->nullable();
			$table->integer('CODCONTATO')->nullable();
			$table->integer('NUAPONTA')->nullable();
			$table->integer('NUMBOR')->nullable();
			$table->float('M2')->nullable();
			$table->string('DIGSAFRA')->length(1)->nullable();
			$table->string('NFENTSEQFIX')->length(15)->nullable();
			$table->integer('NFCOMPLFIX')->nullable();
			$table->integer('CODPARCRESP')->nullable();
			$table->string('PDD')->length(1)->nullable();
			$table->integer('CODUSUCOBR')->nullable();
			$table->string('NUMNFSE')->length(20)->nullable();
			$table->integer('NUIMP')->nullable();
			$table->float('VLRALIBERAR')->nullable();
			$table->float('CONVENIO')->nullable();
			$table->string('CHAVECTE')->length(44)->nullable();
			$table->string('CHAVECTEREF')->length(44)->nullable();
			$table->string('NOMEEMITENTE_CMC7')->length(160)->nullable();
			$table->integer('CODRATEIO')->nullable();
			$table->float('VLRCESSAO')->nullable();
			$table->integer('IDLOTEFDIC')->nullable();
			$table->integer('NRODOCTEF');
			$table->integer('NUPED')->nullable();
			$table->integer('CODBCO_CMC7')->nullable();
			$table->string('AGENCIA_CMC7')->length(5)->nullable();
			$table->string('CONTA_CMC7')->length(14)->nullable();
			$table->string('CGC_CPF_CMC7')->length(14)->nullable();
			$table->integer('CODCC')->nullable();
			$table->string('SITESPECIALRESP')->length(2)->nullable();
			$table->string('EXIGEISSQN')->length(2)->nullable();
			$table->string('REGESPTRIBUT')->length(2)->nullable();
			$table->string('MOTNAORETERISSQN')->length(2)->nullable();
			$table->float('VLRFATCARTAO')->nullable();
			$table->integer('NUCCR')->nullable();
			$table->string('CODCARTAO')->length(50)->nullable();
			$table->integer('NROLOTEGNRE')->nullable();
			$table->string('STATUSGNRE')->length(50)->nullable();
			$table->string('REJEICAOGNRE')->length(500)->nullable();
			$table->integer('NUFTC')->nullable();
			$table->string('PARCRENEG')->length(20)->nullable();
			$table->string('TPAGNFCE')->length(2)->nullable();
			$table->float('VALORPRESENTE')->nullable();
			$table->float('JUROSAVP')->nullable();
			$table->string('BLOQVAR')->length(1)->nullable()->default('N');
			$table->float('VLRFRETENFS')->nullable();
			$table->float('VLRDESCCALC')->nullable();
			$table->float('VLRHONOR')->nullable();
			$table->float('BASEIRF')->nullable();
			$table->float('BASEINSS')->nullable();
			$table->string('MONIOCOREM')->length(1)->nullable();
			$table->string('NSUECONECT')->length(20)->nullable();
			$table->date('DTPRAZO')->nullable();
			$table->float('VLRTROCOECONECT')->nullable();
			$table->string('TIPOTROCOECONECT')->length(1)->nullable();
			$table->string('RECEBCARTAO')->length(1)->nullable();
			$table->float('ABATIMENTO')->nullable();
			$table->float('ABATIMENTOCAN')->nullable();
			$table->float('VLRDESCSSPMB')->nullable();
			$table->string('TIPOABATSSPMB')->length(1)->nullable();
			$table->integer('CODCBE')->nullable();
			$table->string('DESPADVOGADO')->length(1)->nullable();
			$table->string('CUSTASPROCESSUAIS')->length(1)->nullable();
			$table->string('DEPOSITOJUDICIAL')->length(1)->nullable();
			$table->string('NUMPROCADMJUDIC')->length(21)->nullable();
			$table->integer('OBRACONSTCIVIL')->nullable();
			$table->integer('CLASSIFCESSAOOBRA')->nullable();
			$table->integer('CODLST')->nullable();
			$table->integer('CODTRIB')->nullable();
			$table->integer('CODCIDINICTE')->nullable();
			$table->integer('CODCIDFIMCTE')->nullable();
			$table->string('CODOBRA')->length(15)->nullable();
			$table->string('CHEQUERASTREADO_CMC7')->length(1)->nullable();
			$table->integer('NUCHQ')->nullable();
			$table->integer('CODREGUA')->nullable();
			$table->integer('SEQCAIXA')->nullable();
			$table->integer('IDUNICO')->nullable();
			$table->integer('TIMPARCELA')->nullable();
			$table->integer('TIMCONTRATOLOC')->nullable();
			$table->integer('TIMNEGOCIACAO')->nullable();
			$table->date('TIMDTIMPBOL')->nullable();
			$table->date('TIMDTREPASSE')->nullable();
			$table->date('TIMDHBAIXA')->nullable();
			$table->date('TIMDATADEJUR')->nullable();
			$table->integer('TIMNUMREG')->nullable();
			$table->string('TIMORIGEM')->length(2)->nullable();
			$table->integer('TIMNUFINORIG')->nullable();
			$table->integer('TIMVENDAIMV')->nullable();
			$table->integer('TIMRENEGIMV')->nullable();
			$table->integer('TIMVENDALOTE')->nullable();
			$table->integer('TIMRENEGLOTE')->nullable();
			$table->integer('TIMSAC')->nullable();
			$table->string('TIMNOMEADVOGADO')->length(200)->nullable();
			$table->date('TIMDHGERREPASSE')->nullable();
			$table->integer('TIMCONTAREP')->nullable();
			$table->integer('TIMIMOVEL')->nullable();
			$table->integer('TIMCONTRATOADM')->nullable();
			$table->string('TIMBLOQUEADA')->length(1)->nullable()->default('N');
			$table->integer('TIMFECHAMENTOALU')->nullable();
			$table->date('TIMDTIMPBOLLOCAL')->nullable();
			$table->integer('TIMFECHAMENTO')->nullable();
			$table->integer('TIMRENEGCANCLOTE')->nullable();
			$table->integer('TIMCONTRATOLTV')->nullable();
			$table->integer('TIMRESCISAOLTV')->nullable();
			$table->integer('TIMNUNOTA')->nullable();
			$table->integer('TIMCONTALANC')->nullable();
			$table->string('TIMTXADMGERALU')->length(1)->nullable()->default('S');
			$table->integer('TIMFINGARANTORIG')->nullable();
			$table->integer('TIMREPINTELIGENTE')->nullable();
			$table->date('TIMDHGERREPPARCIAL')->nullable();
			$table->date('TIMDTREPPARCIAL')->nullable();
			$table->string('TIMREPPARCIAL')->length(1)->nullable();
			$table->integer('TIMVLRJUROCONTRATO')->nullable();
			$table->integer('TIMVLRAMORTCONTRATO')->nullable();
			$table->integer('TIMVLRCORRMONET')->nullable();
			$table->integer('CODIPTU')->nullable();
			$table->string('TIMORIGRENEG')->length(1)->nullable();
			$table->integer('TIMRESCISAOLOC')->nullable();
			$table->integer('TIMTIPOINTERMED')->nullable();
			$table->integer('CODOBSPADRAO')->nullable();
			$table->integer('CODIMOVELRURAL')->nullable();
			$table->string('RECADIANTAMENTORURAL')->length(1)->nullable();
			$table->integer('NUCKC')->nullable();
			$table->string('CHAVENFEGNRE')->length(44)->nullable();
			$table->integer('NUANTBANC')->nullable();
			$table->string('NUMDOCARRECAD')->length(30)->nullable();
			$table->date('DTENTSAIINFO')->nullable();
			$table->date('REFATCON')->nullable();
			$table->string('FINCONFIRMADO')->length(1)->nullable();
			$table->string('TIPAPURACAO')->length(1)->nullable();
			$table->float('VLRGNREDOIS')->nullable();
			$table->string('DESCRTPAGNFCE')->length(60)->nullable();
			$table->string('RECEBIDO')->length(1)->nullable();
			$table->string('EMVPIX')->length(1000)->nullable();
			$table->float('TROCOPDV')->nullable();
			$table->date('DTINITREFAPURACAO')->nullable();
			$table->date('DHINTEGRACAO')->nullable();
			$table->string('INDRECEFDCONT')->length(2)->nullable();
			$table->string('INFCOMPLEFDCONT')->length(255)->nullable();
			$table->date('DTREFERENCIA')->nullable();
			$table->string('CODRECEITA')->length(10)->nullable();
			$table->date('DTINTEGRACAOIPI')->nullable();
			$table->integer('NUVERBA')->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->string('AD_ID_EXTERNO_CODEMP')->length(100)->nullable();
			$table->string('AD_ID_EXTERNO_CODNAT')->length(100)->nullable();
			$table->string('AD_ID_EXTERNO_CODPARC')->length(100)->nullable();
			$table->float('VLRDESDOBCALC')->nullable();
			$table->string('DESCRTIPTIT')->length(30);
			$table->string('ESPDOC')->length(2)->nullable();
			$table->integer('CARENCIA')->nullable();
			$table->string('FISCAL')->length(30)->nullable();
			$table->string('EXPTES')->length(1)->default('N' );
			$table->integer('EXPGRS');
			$table->float('CARTAOTAXA')->nullable();
			$table->float('CARTAODESC')->nullable();
			$table->string('VALIDAQTDMAXTITVENCIDOS')->length(1)->default('N' );
			$table->string('EXIGBAIXAACERTO')->length(1)->default('N' );
			$table->string('TRANSFDIF')->length(1)->default('N' );
			$table->integer('INDTIT')->default(99);
			$table->string('TRANSFPEND')->length(1)->nullable()->default('N');
			$table->string('TRANSFBAIX')->length(1)->nullable()->default('S');
			$table->float('PERCJUROS')->nullable();
			$table->float('PERCMULTA')->nullable();
			$table->integer('CODMOEDA')->nullable();
			$table->string('EXIBBAIX')->length(250)->nullable();
			$table->integer('CODCTACTB')->nullable();
			$table->integer('CODCTACTB2')->nullable();
			$table->integer('CODCTACTB3')->nullable();
			$table->string('BAIXACERTO')->length(1)->default('S' );
			$table->string('INFCMC7')->length(1)->default('N' );
			$table->string('GRUPOLIMCRED')->length(20)->nullable();
			$table->string('FASTUSA')->length(1)->default('N' );
			$table->text('IMAGEM')->nullable();
			$table->float('PERCCUSVAR')->nullable();
			$table->float('VLRCUSVAR')->nullable();
			$table->string('FASTBAIXA')->length(1)->default('N' );
			$table->integer('PRAZO');
			$table->integer('CODGRUPOTIPTIT');
			$table->string('IMPBOLRENEG')->length(1)->default('N' );
			$table->string('SUBTIPOVENDA')->length(2)->default('0' );
			$table->string('CONFERENCIA')->length(1)->default('N' );
			$table->string('ATIVO')->length(1)->default('S' );
			$table->integer('CODPARCTEF');
			$table->string('IMPCOMPROVANTE')->length(1)->default('N' );
			$table->integer('CODRECGNRE')->nullable();
			$table->integer('CODDETRECGNRE')->nullable();
			$table->integer('CODPRODGNRE')->nullable();
			$table->string('TPAGNFCE')->length(2)->nullable();
			$table->string('AJUSTAVP')->length(1)->default('N' );
			$table->string('UTILIZAPOS')->length(1)->nullable()->default('N');
			$table->integer('NROPARCELAS');
			$table->string('INTEGRAECONECT')->length(1)->default('N' );
			$table->integer('CODFINALIZADORA')->nullable();
			$table->integer('GRUPOFINALIZADORA')->nullable();
			$table->string('CODBANDEIRAECONECT')->length(32)->nullable();
			$table->string('CONVENIOECONECT')->length(1)->default('N' );
			$table->integer('DIAVENC')->nullable();
			$table->string('TIPVENC')->length(1)->nullable();
			$table->string('OPERACAOCTF')->length(3)->nullable();
			$table->integer('QTDPARCELCTF')->nullable();
			$table->string('RECEBANTAPROV')->length(1)->nullable();
			$table->string('ARREDPRIMEIRAPARC')->length(1)->nullable();
			$table->string('TRUNCPARCELA')->length(1)->nullable();
			$table->string('TIMUSADOLOCACAO')->length(1)->nullable();
			$table->string('TIPDOCRURAL')->length(1)->nullable();
			$table->string('PROIBIMPBOL')->length(1)->nullable();
			$table->string('ALTERASIMULTPV')->length(1)->nullable();
			$table->string('DESCRTPAGNFCE')->length(60)->nullable();
			$table->string('INDRECEFDCONT')->length(2)->nullable();
			$table->string('INFCOMPLEFDCONT')->length(255)->nullable();
			$table->string('CONSDIASUTEIS')->length(1)->nullable();
			$table->string('CREDENCIADORACFE')->length(5)->nullable();
			$table->string('UTILIZAPIXSITEF')->length(1)->nullable();
			$table->string('DESCRPROD')->length(100);
			$table->string('COMPLDESC')->length(40)->nullable();
			$table->string('CARACTERISTICAS')->length(4000)->nullable();
			$table->string('REFERENCIA')->length(15)->nullable();
			$table->integer('CODGRUPOPROD');
			$table->string('CODVOL')->length(2);
			$table->string('MARCA')->length(10)->nullable();
			$table->string('LOCALIZACAO')->length(15)->nullable();
			$table->integer('CODIPI')->nullable();
			$table->integer('CLASSUBTRIB')->nullable();
			$table->integer('CODFORMPREC')->nullable();
			$table->float('MARGLUCRO')->nullable();
			$table->float('MULTIPVENDA')->nullable();
			$table->integer('DECCUSTO')->nullable();
			$table->integer('DECVLR')->nullable();
			$table->integer('DECQTD')->nullable();
			$table->float('COMGER')->nullable();
			$table->float('COMVEND')->nullable();
			$table->float('DESCMAX')->nullable();
			$table->float('PESOBRUTO');
			$table->float('PESOLIQ');
			$table->float('MEDAUX')->nullable();
			$table->integer('PRAZOVAL')->nullable();
			$table->float('AGRUPMIN')->nullable();
			$table->integer('QTDEMB')->nullable();
			$table->string('ALERTAESTMIN')->length(1)->default('S' );
			$table->string('PROMOCAO')->length(1)->default('N' );
			$table->string('TEMICMS')->length(1)->default('N' );
			$table->string('TEMISS')->length(1)->default('N' );
			$table->string('TEMIPIVENDA')->length(1)->default('N' );
			$table->string('TEMIPICOMPRA')->length(1)->default('N' );
			$table->string('TEMIRF')->length(1)->default('N' );
			$table->float('PERCIRF')->nullable();
			$table->string('TEMINSS')->length(1)->default('N' );
			$table->float('PERCINSS');
			$table->float('REDBASEINSS');
			$table->string('USOPROD')->length(1)->nullable()->default('V');
			$table->string('ORIGPROD')->length(1)->nullable()->default('0');
			$table->string('TIPSUBST')->length(1)->nullable()->default('N');
			$table->float('CODICMSFAST')->nullable();
			$table->string('TIPLANCNOTA')->length(1)->nullable()->default('A');
			$table->string('TIPCONTEST')->length(1)->nullable()->default('N');
			$table->integer('CODTAB')->nullable();
			$table->integer('CODCTACTB')->nullable();
			$table->text('IMAGEM')->nullable();
			$table->string('ATIVO')->length(1)->default('S' );
			$table->float('ESTMAX')->nullable();
			$table->float('ESTMIN')->nullable();
			$table->string('APRESDETALHE')->length(1)->default('N' );
			$table->string('SELECIONADO')->length(1)->nullable();
			$table->string('TITCONTEST')->length(10)->nullable();
			$table->string('LISCONTEST')->length(4000)->nullable();
			$table->integer('CODMOEDA');
			$table->integer('GRUPOICMS')->nullable();
			$table->float('PERCAUMENTCUSTO')->nullable();
			$table->string('LOCAL')->length(1)->default('N' );
			$table->date('DTALTER');
			$table->string('USALOCAL')->length(1)->default('N' );
			$table->string('HOMEPAGE')->length(255)->nullable();
			$table->integer('CODCTACTB2')->nullable();
			$table->integer('CODCTACTB3')->nullable();
			$table->date('TEMPOSERV')->nullable();
			$table->string('ENDIMAGEM')->length(200)->nullable();
			$table->integer('CODUSU');
			$table->integer('CODPARCFORN')->nullable();
			$table->string('CODVOLCOMPRA')->length(2)->nullable()->default('0');
			$table->string('CODPRODROI')->length(2)->nullable();
			$table->string('GRUPODESCPROD')->length(15)->nullable();
			$table->string('REFFORN')->length(30)->nullable();
			$table->string('HRDOBRADA')->length(1)->default('N' );
			$table->string('ICMSGERENCIA')->length(1)->default('N' );
			$table->integer('CODNAT');
			$table->integer('CODCENCUS');
			$table->integer('CODPROJ');
			$table->float('M3')->nullable();
			$table->string('TEMCIAP')->length(1)->default('N' );
			$table->string('IMPLAUDOLOTE')->length(1)->default('N' );
			$table->integer('CODGAR')->nullable();
			$table->string('DIMENSOES')->length(1)->default('N' );
			$table->float('PERCQUEBRATEC')->nullable();
			$table->integer('CODCTACTB4')->nullable();
			$table->integer('CODFILTRO')->nullable();
			$table->integer('CODGENERO')->nullable();
			$table->integer('CODLST')->nullable();
			$table->string('PADRAO')->length(1)->default('S' );
			$table->string('ENDMODROTULO')->length(255)->nullable();
			$table->string('NATUREZAOPERDES')->length(2)->nullable();
			$table->integer('CNAE')->nullable();
			$table->string('SOLCOMPRA')->length(1)->default('N' );
			$table->string('CONFERE')->length(1)->default('S' );
			$table->string('REMETER')->length(1)->default('N' );
			$table->string('MOTIVOINCEXC')->length(1)->nullable();
			$table->integer('ARREDPRECO')->nullable();
			$table->string('TEMCOMISSAO')->length(1)->default('S' );
			$table->string('COMPONOBRIG')->length(1)->nullable();
			$table->string('FATTOTAL')->length(1)->nullable();
			$table->string('NOMETAB')->length(32)->nullable();
			$table->string('AP1RCTEGO')->length(1)->default('N' );
			$table->string('CALCULOGIRO')->length(1)->default('E' );
			$table->float('REDBASEIRF')->nullable();
			$table->float('ALTURA')->nullable();
			$table->float('LARGURA')->nullable();
			$table->float('ESPESSURA')->nullable();
			$table->string('UNIDADE')->length(2)->default('MM' );
			$table->integer('CODFORMAPONTA')->nullable();
			$table->integer('CODCOS')->nullable();
			$table->string('CONFCEGAPESO')->length(1)->default('N' );
			$table->integer('ORDCALCCUSTPROD')->nullable();
			$table->string('REGRAWMS')->length(1)->default('O' );
			$table->string('GRUPOPIS')->length(30)->default('TODOS' );
			$table->string('GRUPOCOFINS')->length(30)->default('TODOS' );
			$table->string('GRUPOCSSL')->length(30)->default('TODOS' );
			$table->integer('CSTIPIENT')->nullable();
			$table->integer('CSTIPISAI')->nullable();
			$table->string('STATUSINCEXC')->length(1)->nullable();
			$table->string('UTILIZAWMS')->length(1)->default('N' );
			$table->string('BALANCA')->length(1)->default('N' );
			$table->integer('CODPAIS')->nullable();
			$table->string('RENDIMENTO')->length(50)->nullable();
			$table->string('OBSETIQUETA')->length(120)->nullable();
			$table->integer('CODANP')->nullable();
			$table->string('CODAUTCODIF')->length(21)->nullable();
			$table->integer('CODPRODAGRUPAPT')->nullable();
			$table->integer('CODPRODAGRUPAPTENC')->nullable();
			$table->string('CULTURA')->length(80)->nullable();
			$table->string('CIENTIFICO')->length(80)->nullable();
			$table->integer('CLASSEAGT')->nullable();
			$table->integer('GRUPOQUIMICO')->nullable();
			$table->integer('CLASSETOX')->nullable();
			$table->integer('PRINCATIVO')->nullable();
			$table->string('FORMULACAO')->length(180)->nullable();
			$table->string('CONCENTRACAO')->length(30)->nullable();
			$table->string('MODOAPLIC')->length(240)->nullable();
			$table->string('EPOCAAPLIC')->length(120)->nullable();
			$table->string('MANEJOINT')->length(120)->nullable();
			$table->float('DOSAGEM')->nullable();
			$table->string('VOLDOSAGEM')->length(2)->nullable();
			$table->float('DOSAGEMPOR')->nullable();
			$table->string('VOLDOSAGEMPOR')->length(2)->nullable();
			$table->string('RENDIMENTOPR')->length(15)->nullable();
			$table->string('RECEITUARIO')->length(1)->nullable()->default('N');
			$table->string('EXIGEBENEFIC')->length(1)->nullable()->default('N');
			$table->string('TIPOCLASSEAGT')->length(1)->nullable();
			$table->string('TIPOGRUPOQUIMICO')->length(1)->nullable();
			$table->string('TIPOPRINCATIVO')->length(1)->nullable();
			$table->string('TIPOCLASSETOX')->length(1)->nullable();
			$table->integer('GRUPOTRANSG')->nullable();
			$table->string('GERAPLAPROD')->length(1)->default('N' );
			$table->integer('APLICACAO')->nullable();
			$table->integer('INTERVALO')->nullable();
			$table->integer('CARENCIA')->nullable();
			$table->float('RENDIMENTOHA')->nullable();
			$table->integer('PRODUTONFE');
			$table->integer('TIPGTINNFE')->default(2);
			$table->string('NCM')->length(10)->nullable();
			$table->string('CODVOLPLAN')->length(2)->nullable();
			$table->float('DESCMAXFLEX')->nullable();
			$table->float('ACRESCMAX')->nullable();
			$table->string('FLEX')->length(1)->default('S' );
			$table->integer('NUMITEMREA')->nullable();
			$table->string('IMPRIMIR')->length(1)->default('0' );
			$table->string('CONFIRMAIMP')->length(1)->default('N' );
			$table->string('APURAPRODEPE')->length(2)->nullable();
			$table->string('INDESPPRODEPE')->length(2)->nullable();
			$table->integer('QTDNFLAUDOSINT');
			$table->string('CODTRIBMUNISS')->length(20)->nullable();
			$table->string('TIPCONTESTWMS')->length(1)->default('N' );
			$table->string('LISTALPM')->length(1)->default('N' );
			$table->string('ONEROSO')->length(1)->default('N' );
			$table->string('REFMERCMED')->length(1)->default('N' );
			$table->string('TERMOLABIL')->length(1)->default('N' );
			$table->float('TEMPMINIMA')->nullable();
			$table->float('TEMPMAXIMA')->nullable();
			$table->string('CONTROLADO')->length(1)->default('N' );
			$table->string('IDENPORTARIA')->length(30)->nullable();
			$table->string('IDENOTC')->length(30)->nullable();
			$table->string('IDENCORRELATO')->length(1)->default('N' );
			$table->string('IDENCOSME')->length(1)->default('N' );
			$table->string('PRODFALTA')->length(1)->default('N' );
			$table->integer('CODFAB')->nullable();
			$table->integer('STATUSMED');
			$table->integer('CODCPR')->nullable();
			$table->integer('SEQSPR')->nullable();
			$table->integer('SEQSCA')->nullable();
			$table->integer('SEQSTE')->nullable();
			$table->integer('CODCAT')->nullable();
			$table->integer('CODTER')->nullable();
			$table->integer('CODPAT')->nullable();
			$table->float('MVAAJUSTADO');
			$table->string('INFPUREZA')->length(1)->default('N' );
			$table->string('FABRICANTE')->length(80)->nullable();
			$table->string('USASTATUSLOTE')->length(1)->default('N' );
			$table->integer('TAMLOTE')->nullable();
			$table->integer('TAMSERIE')->nullable();
			$table->string('UNIDMINARMAZ')->length(2)->nullable();
			$table->string('ORIGEMFAT')->length(1)->default('E' );
			$table->string('USACODBARRASQTD')->length(1)->default('N' );
			$table->string('MD5PAF')->length(32)->nullable();
			$table->string('VALCAPM3')->length(1)->default('N' );
			$table->string('QTDPECAFRAC')->length(1)->default('N' );
			$table->string('UTILORDCORTE')->length(1)->default('N' );
			$table->integer('CODPRODPERDA')->nullable();
			$table->string('DESCRUTILBEM')->length(4000)->nullable();
			$table->string('IMPORDEMCORTE')->length(1)->default('N' );
			$table->float('PERCTROCA');
			$table->integer('CORFONTCONSPRECO')->nullable();
			$table->integer('CORFUNDOCONSPRECO')->nullable();
			$table->string('CODVOLRES')->length(2)->nullable();
			$table->integer('CODAREASEP')->nullable();
			$table->integer('IDENTIMOB')->nullable();
			$table->integer('UTILIMOB')->nullable();
			$table->string('TEMCREDPISCOFINSDEPR')->length(1)->default('N' );
			$table->integer('CODPRODINNATURA')->nullable();
			$table->string('UTILSMARTCARD')->length(1)->default('N' );
			$table->string('RECUPAVARIA')->length(1)->default('N' );
			$table->float('CONVERVOL')->nullable();
			$table->integer('LASTRO')->nullable();
			$table->integer('CAMADAS')->nullable();
			$table->float('ORDEMMEDIDA')->nullable();
			$table->float('ALIQICMSINTEFD')->nullable();
			$table->string('CODREGMAPA')->length(20)->nullable();
			$table->string('APRESFORM')->length(1)->default('S' );
			$table->string('CODBARCOMP')->length(1)->default('N' );
			$table->string('TEMMEDICAO')->length(1)->default('N' );
			$table->integer('CODFILTROREQ')->nullable();
			$table->string('NATBCPISCOFINS')->length(1)->default('D' );
			$table->string('CONTARPORPESO')->length(1)->default('N' );
			$table->integer('CODLOCALPADRAO')->nullable();
			$table->string('PERMCOMPPROD')->length(1)->default('S' );
			$table->integer('CODEXNCM');
			$table->integer('QTDCST');
			$table->integer('DIASCST');
			$table->integer('PERCTOLVARCST')->default(100);
			$table->float('QTDPEDPEND')->nullable();
			$table->integer('LEADTIME')->nullable();
			$table->integer('DIASEXPEDICAO')->nullable();
			$table->string('DTVALDIF')->length(1)->default('X' );
			$table->integer('SHELFLIFEMIN')->nullable();
			$table->integer('SHELFLIFE')->nullable();
			$table->string('CODBARBALANCA')->length(1)->default('N' );
			$table->string('VALCBGLOBAL')->length(1)->default('N' );
			$table->string('USAPONTOS')->length(1)->default('N' );
			$table->integer('CODRFA')->nullable();
			$table->integer('PERCROYALTY')->nullable();
			$table->string('INTEGRAECONECT')->length(1)->default('N' );
			$table->string('ENQREINTEGRA')->length(1)->default('N' );
			$table->float('PERCCMTNAC');
			$table->float('PERCCMTIMP');
			$table->string('CODATIVREINTEGRA')->length(8)->nullable();
			$table->string('NOTIFCONF')->length(500)->nullable();
			$table->string('USASERIEFAB')->length(1)->nullable();
			$table->string('TIPSERNFE')->length(1)->nullable();
			$table->string('VENCOMPINDIV')->length(1)->nullable();
			$table->string('EXCLUIRCONF')->length(1)->nullable();
			$table->string('PRODUZAUT')->length(1)->default('N' );
			$table->string('USAIMPAGRUPMIN')->length(1)->default('S' );
			$table->string('RASTRESTOQUE')->length(1)->default('N' );
			$table->string('IMPETIQCONF')->length(1)->default('S' );
			$table->float('VLRCOMERC')->nullable();
			$table->float('VLRPARCIMPEXT')->nullable();
			$table->string('CODFCI')->length(36)->nullable();
			$table->string('SERVPARAINDUST')->length(1)->default('N' );
			$table->string('DESCRPRODNFE')->length(100)->nullable();
			$table->string('CAT1799SPRES')->length(1)->default('N' );
			$table->float('ALIQNAC')->nullable();
			$table->float('ALIQIMP')->nullable();
			$table->float('ESTSEGQTD');
			$table->integer('ESTSEGDIAS')->nullable();
			$table->date('DTALTERESQ')->nullable();
			$table->integer('LOTECOMPRAS')->nullable();
			$table->float('ESTMAXQTD');
			$table->integer('ESTMAXDIAS')->nullable();
			$table->date('DTALTEREMQ')->nullable();
			$table->float('DESVIOMAX');
			$table->float('ARREDAGRUP')->default(0.5 );
			$table->string('APLICASAZO')->length(1)->default('S' );
			$table->float('LOTECOMPMINIMO');
			$table->float('AGRUPCOMPMINIMO');
			$table->string('USASERIESEPWMS')->length(1)->default('N' );
			$table->string('GERACUSTCOMPSEG')->length(1)->default('N' );
			$table->integer('TOPFATURCON')->nullable();
			$table->string('SERFATURCON')->length(3)->nullable();
			$table->integer('CODGPROD')->nullable();
			$table->string('EXIGELASTROCAMADAS')->length(1)->nullable()->default('S');
			$table->string('FIXOAGENDA')->length(1)->default('S' );
			$table->integer('CODPARCCONSIG')->nullable();
			$table->string('USALOTEDTVAL')->length(1)->nullable();
			$table->string('USALOTEDTFAB')->length(1)->nullable();
			$table->string('EXIBCOMPEXPKIT')->length(1)->default('T' );
			$table->integer('TIPORECEITAMOD21')->nullable();
			$table->integer('CODPRODSUBST')->nullable();
			$table->date('DTSUBST')->nullable();
			$table->integer('CODCOMP')->nullable();
			$table->integer('NATEFDCONTM410M810')->nullable();
			$table->float('PERCTOLPESOMAIOR')->nullable();
			$table->float('PERCTOLPESOMENOR')->nullable();
			$table->string('CODVOLPESOVAR')->length(2)->nullable();
			$table->string('USACONTPESOVAR')->length(1)->nullable();
			$table->float('PERCTOLPESOMAIORSEP')->nullable();
			$table->float('PERCTOLPESOMENORSEP')->nullable();
			$table->float('PCT_BF')->nullable();
			$table->integer('PRZ_BF')->nullable();
			$table->string('CONTROLMEDIC')->length(1)->nullable();
			$table->integer('DECVLRENT')->nullable();
			$table->float('PERCCMTFED');
			$table->float('PERCCMTEST');
			$table->float('PERCCMTMUN');
			$table->integer('CODENQIPIENT')->nullable();
			$table->integer('CODENQIPISAI')->nullable();
			$table->string('DESCVENCONSUL')->length(1)->nullable()->default('N');
			$table->integer('GRUPOICMS2')->nullable();
			$table->float('MVAPADRAO')->nullable();
			$table->float('ALIQGERAL')->nullable();
			$table->integer('CODPRODSUBKIT')->nullable();
			$table->integer('CODCONFKIT')->nullable();
			$table->string('TIPOKIT')->length(1)->nullable();
			$table->integer('CODESPECST')->nullable();
			$table->string('VISIVELAPPOS')->length(1)->nullable();
			$table->string('UTILIZAENDFLUT')->length(1)->nullable()->default('N');
			$table->integer('MAXMULTECONECT')->nullable();
			$table->integer('CODVTP')->nullable();
			$table->integer('QTDIDENTIF')->nullable();
			$table->string('TIPOIDENTIF')->length(50)->nullable();
			$table->integer('MODETIQSEPWMS')->nullable();
			$table->string('IMPETIQSEPWMS')->length(1)->nullable();
			$table->string('NROPROCESSO')->length(30)->nullable();
			$table->integer('TIPOSN')->nullable();
			$table->string('ARMAZELOTE')->length(1)->default('N' );
			$table->string('TEMRASTROLOTE')->length(1)->default('N' );
			$table->string('CODANVISA')->length(13)->nullable();
			$table->string('DESCRANP')->length(95)->nullable();
			$table->float('PERCMISTGLP')->nullable();
			$table->integer('CODSERVTELECOM')->nullable();
			$table->string('TIPOCONTAGEM')->length(1)->default('D' );
			$table->integer('CODMARCA')->nullable();
			$table->float('PERCMISTGNN')->nullable();
			$table->float('PERCMISTGNI')->nullable();
			$table->float('VLRPARTIDAGLP')->nullable();
			$table->integer('CODCTACTBEFD')->nullable();
			$table->string('CODCPRB')->length(8)->nullable();
			$table->string('COMERCIALIZACAOAGRI')->length(1)->nullable();
			$table->integer('OBRACONSTCIVIL')->nullable();
			$table->integer('CLASSIFCESSAOOBRA')->nullable();
			$table->string('TIPOINSSESPECIAL')->length(1)->nullable();
			$table->float('PERCINSSESPECIAL')->nullable();
			$table->string('CALCDIFAL')->length(1)->default('N' );
			$table->string('INDESCALA')->length(1)->nullable();
			$table->string('CNPJFABRICANTE')->length(14)->nullable();
			$table->string('CODBENEFNAUF')->length(10)->nullable();
			$table->string('CODAGREGACAO')->length(20)->nullable();
			$table->float('QTDAGRUPAMENTOMTZ')->nullable();
			$table->integer('CODIDCNAE')->nullable();
			$table->integer('CODFILTROCTA')->nullable();
			$table->string('FORCAEXPECONECT')->length(1)->nullable();
			$table->string('REGISTRARPESO')->length(2)->nullable();
			$table->integer('DESVIOMAXTOLCONFSEP')->nullable();
			$table->integer('DESVIOMINTOLCONFSEP')->nullable();
			$table->string('SERVPRESTTER')->length(1)->nullable();
			$table->string('FRAGMENTALOTE')->length(1)->nullable()->default('N');
			$table->float('PERCREDBASEICMSEFET')->nullable();
			$table->integer('NUVERSAOIMG')->nullable();
			$table->integer('INTEGRAFOX')->nullable();
			$table->integer('NUVERSAO')->nullable();
			$table->string('MOTISENCAOANVISA')->length(255)->nullable();
			$table->string('CODNBS')->length(9)->nullable();
			$table->string('CONSPRODCAT42')->length(1)->nullable();
			$table->string('TIPOITEMSPED')->length(2)->nullable();
			$table->float('INCPESOBRUTO')->nullable();
			$table->float('INCPESOLIQUIDO')->nullable();
			$table->integer('NURFE')->nullable();
			$table->float('MVAORIGINALDRCST')->nullable();
			$table->float('TAMANHOMEDIOPECA')->nullable();
			$table->integer('IDGRADE')->nullable();
			$table->float('PERCENTSEPPUL')->nullable();
			$table->string('ATUNUVERSAO')->length(1)->nullable();
			$table->text('GRADEPADRAO')->nullable();
			$table->float('ALIQFETHAB')->nullable();
			$table->string('CODVOLFETHAB')->length(2)->nullable();
			$table->string('OBTSTANTMEDENT')->length(1)->nullable();
			$table->string('DESCPRODDRCST')->length(1)->nullable();
			$table->string('PARTICIPAADRCST')->length(1)->nullable();
			$table->float('MVAORIGINALADRCST')->nullable();
			$table->float('ALIQFECOP')->nullable();
			$table->string('PRODSUJFECOP')->length(1)->nullable();
			$table->string('DESDESCCALCPIS')->length(1)->nullable();
			$table->float('ALIQINTERNACAT42')->nullable();
			$table->string('CONESTORIGPROD')->length(1)->nullable();
			$table->string('GERIMPNRETREINFAQ')->length(1)->nullable();
			$table->string('PRODALIADRCST')->length(1)->nullable();
			$table->integer('TIPUTILCOM')->nullable();
			$table->string('PRODINTERNO')->length(1)->nullable();
			$table->string('CALCFUSTPRO')->length(1)->nullable();
			$table->string('CALCFUNTTELPRO')->length(1)->nullable();
			$table->string('CODBARDIFGTIN')->length(30)->nullable();
			$table->string('CODBARTRIBDIFGTIN')->length(30)->nullable();
			$table->string('WMSPRODRASTSERMED')->length(1)->nullable();
			$table->string('STATUSNCM')->length(1)->nullable();
			$table->string('BLOQVENDAFRAC')->length(1)->nullable();
			$table->string('AD_EXTERNO_CODGRUPOPROD')->length(100)->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->integer('AD_CODCENCUSCOM');
			$table->integer('AD_CODNATCOM');
			$table->integer('AD_CODEMP')->nullable();
			$table->integer('TPIRRFEXT')->nullable();
			$table->integer('CODNATREND')->nullable();
			$table->string('INDTIPREFBCICMSST')->length(1)->nullable();
			$table->integer('CODEMP');
			$table->string('CTACTB')->length(30);
			$table->integer('GRAU');
			$table->string('DESCRCTA')->length(40);
			$table->string('ANALITICA')->length(1)->nullable()->default('N');
			$table->string('CENCUSOBRIG')->length(1)->default('N' );
			$table->string('CONVSALDOMOEDA')->length(1)->nullable()->default('I');
			$table->string('DTBASECONVMOEDA')->length(1)->nullable();
			$table->integer('CODCTACTBPAI');
			$table->string('ATIVA')->length(1)->default('S' );
			$table->integer('PRODUTO')->nullable();
			$table->integer('PLANTA')->nullable();
			$table->integer('PROCESSO')->nullable();
			$table->string('BEMORIGINAL')->length(1)->default('N' );
			$table->string('BEMRESREAV')->length(1)->default('N' );
			$table->string('BEMOUTROS')->length(1)->default('N' );
			$table->string('OBSERVACOES')->length(4000)->nullable();
			$table->string('PODELANCTOMANUAL')->length(1)->default('S' );
			$table->date('DTINCLUSAO')->nullable();
			$table->string('CODGRUPOCTA')->length(2)->nullable();
			$table->string('CODCTAREF')->length(30)->nullable();
			$table->string('RAZAOAUXSPED')->length(1)->default('N' );
			$table->integer('CODCTACTBSUBST');
			$table->date('DTINATIV')->nullable();
			$table->integer('CODUSU');
			$table->date('DTALTER')->default(SYSDATE );
			$table->string('PROJOBRIG')->length(1)->default('N' );
			$table->string('LALUR')->length(1)->nullable();
			$table->string('LALUR_A')->length(6)->nullable()->default('0');
			$table->integer('TIPSALALUR')->nullable();
			$table->string('CODCTAREF_FCONT')->length(30)->nullable();
			$table->string('TABELA')->length(6)->nullable();
			$table->integer('CODRAZAUX')->nullable();
			$table->string('DISPSPED')->length(1)->nullable();
			$table->integer('NATUREZAEFD')->nullable();
			$table->string('LALUR_A_CRED')->length(6)->nullable();
			$table->string('TABELACRED')->length(6)->nullable();
			$table->string('RECDESP')->length(1)->nullable();
			$table->string('CLASSIFIRPJ')->length(1)->nullable();
			$table->string('CLASSIFCSLL')->length(1)->nullable();
			$table->string('ADICOESIRPJ')->length(1)->nullable();
			$table->string('CONRESULTIRPJ')->length(1)->nullable();
			$table->string('EXCLUSOESIRPJ')->length(1)->nullable();
			$table->string('PAT4IRPJ')->length(1)->nullable();
			$table->string('ZERACRIRPJ')->length(1)->nullable();
			$table->string('ADICOESCSLL')->length(1)->nullable();
			$table->string('CONRESULTCSLL')->length(1)->nullable();
			$table->string('EXCLUSOESCSLL')->length(1)->nullable();
			$table->string('ZERACRCSLL')->length(1)->nullable();
			$table->string('CODLALURB')->length(10)->nullable();
			$table->string('INDTRIBLALURB')->length(1)->nullable();
			$table->integer('CODCONTA')->nullable();
			$table->string('DESCRCONTA')->length(50)->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->float('QTDATENDIDA')->nullable();
			$table->float('CUSATEND')->nullable();
			$table->integer('ORDEMPROD')->nullable();
			$table->string('STATUSNOTA')->length(1)->default('P' );
			$table->string('FIXACAO')->length(1)->nullable();
			$table->integer('NROMEMORANDO')->nullable();
			$table->string('NROREGEXPORT')->length(12)->nullable();
			$table->string('NROATOCONCDRAW')->length(11)->nullable();
			$table->integer('CODEMP');
			$table->integer('CODCENCUS');
			$table->integer('NUMNOTA');
			$table->string('SERIENOTA')->length(3)->nullable();
			$table->date('DTNEG');
			$table->date('DTFATUR')->nullable();
			$table->date('DTENTSAI')->nullable();
			$table->date('DTVAL')->nullable();
			$table->date('DTMOV')->nullable();
			$table->date('DTCONTAB')->nullable();
			$table->integer('HRMOV')->nullable();
			$table->integer('CODEMPNEGOC');
			$table->integer('CODPARC');
			$table->integer('CODCONTATO')->nullable();
			$table->string('RATEADO')->length(1)->default('N' );
			$table->integer('CODVEICULO');
			$table->integer('CODTIPOPER');
			$table->date('DHTIPOPER');
			$table->string('TIPMOV')->length(1)->default('P' );
			$table->integer('CODTIPVENDA');
			$table->date('DHTIPVENDA')->default(TO_DATE('01/01/1998', 'DD/MM/YYYY') );
			$table->integer('NUMCOTACAO')->nullable();
			$table->integer('CODVEND');
			$table->float('COMISSAO');
			$table->integer('CODMOEDA');
			$table->integer('CODOBSPADRAO');
			$table->string('OBSERVACAO')->length(4000)->nullable();
			$table->float('VLRSEG');
			$table->float('VLRICMSSEG');
			$table->float('VLRDESTAQUE');
			$table->float('VLRJURO');
			$table->float('VLRVENDOR');
			$table->float('VLROUTROS');
			$table->float('VLREMB');
			$table->float('VLRICMSEMB');
			$table->float('VLRDESCSERV');
			$table->float('IPIEMB');
			$table->string('TIPIPIEMB')->length(1)->default('N' );
			$table->float('VLRDESCTOT');
			$table->float('VLRDESCTOTITEM');
			$table->float('VLRFRETE');
			$table->float('ICMSFRETE');
			$table->float('BASEICMSFRETE');
			$table->string('TIPFRETE')->length(1)->default('S' );
			$table->string('CIF_FOB')->length(1)->nullable();
			$table->date('VENCFRETE')->nullable();
			$table->float('VLRNOTA');
			$table->date('VENCIPI')->nullable();
			$table->integer('ORDEMCARGA')->nullable();
			$table->integer('SEQCARGA')->nullable();
			$table->integer('KMVEICULO')->nullable();
			$table->integer('CODPARCTRANSP');
			$table->integer('QTDVOL');
			$table->string('PENDENTE')->length(1)->default('S' );
			$table->float('BASEICMS');
			$table->float('VLRICMS');
			$table->float('BASEIPI');
			$table->float('VLRIPI');
			$table->string('ISSRETIDO')->length(1)->default('S' );
			$table->float('BASEISS');
			$table->float('VLRISS');
			$table->string('APROVADO')->length(1)->default('S' );
			$table->string('STATUSNOTA')->length(1)->default('P' );
			$table->integer('CODUSU')->nullable();
			$table->string('IRFRETIDO')->length(1)->default('N' );
			$table->float('COMGER')->nullable();
			$table->float('VLRIRF');
			$table->date('DTALTER');
			$table->string('VOLUME')->length(60)->nullable();
			$table->integer('CODPARCDEST');
			$table->float('VLRSUBST');
			$table->float('BASESUBSTIT');
			$table->integer('CODPROJ');
			$table->integer('NUMCONTRATO');
			$table->float('BASEINSS');
			$table->float('VLRINSS');
			$table->float('VLRREPREDTOT');
			$table->float('PERCDESC');
			$table->integer('CODPARCREMETENTE');
			$table->integer('CODPARCCONSIGNATARIO');
			$table->integer('CODPARCREDESPACHO');
			$table->string('LOCALCOLETA')->length(40)->nullable();
			$table->string('LOCALENTREGA')->length(40)->nullable();
			$table->float('VLRMERCADORIA')->nullable();
			$table->float('PESO')->nullable();
			$table->string('NOTASCF')->length(35)->nullable();
			$table->integer('CODNAT');
			$table->integer('CODMAQ')->nullable();
			$table->integer('CODFUNC')->nullable();
			$table->integer('NUMOS')->nullable();
			$table->integer('NUMCF')->nullable();
			$table->float('VLRFRETECPL')->nullable();
			$table->float('TROCO');
			$table->integer('NROREDZ')->nullable();
			$table->float('VLRMOEDA')->nullable();
			$table->integer('OCCN48')->nullable();
			$table->integer('CODUSUINC')->nullable();
			$table->integer('NUTRANSF')->nullable();
			$table->integer('CODUSUCOMPRADOR');
			$table->integer('CODSITE')->nullable();
			$table->float('TOTALCUSTOPROD')->nullable();
			$table->float('TOTALCUSTOSERV')->nullable();
			$table->integer('CODCID')->nullable();
			$table->float('BASESUBSTSEMRED')->nullable();
			$table->integer('CODMOTORISTA')->nullable();
			$table->integer('NURD8')->nullable();
			$table->string('NATUREZAOPERDES')->length(2)->nullable();
			$table->string('SERIENFDES')->length(4)->nullable();
			$table->string('MODELONFDES')->length(2)->nullable();
			$table->date('DTPREVENT')->nullable();
			$table->integer('NUNOTAPEDFRET')->nullable();
			$table->float('BASEIRF')->nullable();
			$table->float('ALIQIRF')->nullable();
			$table->string('PLACA')->length(10)->nullable();
			$table->integer('UFVEICULO')->nullable();
			$table->float('PESOBRUTO')->nullable();
			$table->date('HRENTSAI')->nullable();
			$table->string('ANTT')->length(20)->nullable();
			$table->string('LACRES')->length(255)->nullable();
			$table->integer('DANFE')->nullable();
			$table->string('CHAVENFE')->length(44)->nullable();
			$table->string('NUMERACAOVOLUMES')->length(60)->nullable();
			$table->date('DTENVIOPMB')->nullable();
			$table->string('TIPNOTAPMB')->length(10)->nullable();
			$table->integer('NUMALEATORIO')->nullable();
			$table->string('NUMPROTOC')->length(15)->nullable();
			$table->date('DHPROTOC')->nullable();
			$table->date('DTENVSUF')->nullable();
			$table->integer('NULOTENFE')->nullable();
			$table->string('STATUSNFE')->length(1)->nullable();
			$table->integer('TPEMISNFE')->nullable();
			$table->date('DTADIAM')->nullable();
			$table->integer('HRADIAM')->nullable();
			$table->integer('CODDOCA')->nullable();
			$table->string('DIGITAL')->length(1000)->nullable();
			$table->float('TOTDISPDESC')->nullable();
			$table->float('BASEPIS')->nullable();
			$table->float('VLRPIS')->nullable();
			$table->float('BASEPISST')->nullable();
			$table->float('VLRPISST')->nullable();
			$table->float('BASECOFINS')->nullable();
			$table->float('VLRCOFINS')->nullable();
			$table->float('BASECOFINSST')->nullable();
			$table->float('VLRCOFINSST')->nullable();
			$table->float('VLRROYALT')->nullable();
			$table->integer('NROCAIXA')->nullable();
			$table->string('NUMREGDPEC')->length(15)->nullable();
			$table->date('DHREGDPEC')->nullable();
			$table->integer('CODEMPFUNC')->nullable();
			$table->float('VLRINDENIZ')->nullable();
			$table->string('MARCA')->length(60)->nullable();
			$table->integer('TIPOPTAGJNFE')->nullable();
			$table->integer('TPEMISNFSE')->nullable();
			$table->integer('NULOTENFSE')->nullable();
			$table->string('NUMNFSE')->length(20)->nullable();
			$table->string('STATUSNFSE')->length(1)->nullable();
			$table->string('UFEMBARQ')->length(2)->nullable();
			$table->string('LOCEMBARQ')->length(60)->nullable();
			$table->integer('TPLIGACAO')->nullable();
			$table->string('CODGRUPOTENSAO')->length(2)->nullable();
			$table->integer('TPASSINANTE')->nullable();
			$table->integer('NUREM')->nullable();
			$table->string('AGRUPBOL')->length(1)->nullable()->default('N');
			$table->string('RETDATACRITICA')->length(1)->nullable();
			$table->float('QTDBATIDAS')->nullable();
			$table->float('PERCPUREZA')->nullable();
			$table->float('PERCGERMIN')->nullable();
			$table->float('FRETEVLRBRUTO')->nullable();
			$table->float('FRETEVLRDESC')->nullable();
			$table->float('FRETEPERCDESC')->nullable();
			$table->float('FRETEVLRIMP')->nullable();
			$table->float('FRETEVLRJUR')->nullable();
			$table->float('FRETEVLRPAGO')->nullable();
			$table->integer('CODVENDTEC')->nullable();
			$table->integer('NUMPEDIDO')->nullable();
			$table->float('VLRINDENIZDIST')->nullable();
			$table->string('NUMPEDIDO2')->length(15)->nullable();
			$table->integer('CODAGENDA')->nullable();
			$table->date('DTREF')->nullable();
			$table->float('FRETEVLRNEGOC')->nullable();
			$table->integer('CODPRODPERMUTA')->nullable();
			$table->integer('NROGAR')->nullable();
			$table->string('MD5PAF')->length(32)->nullable();
			$table->integer('CODMODDOCNOTA')->nullable();
			$table->string('CPFCNPJADQUIRENTE')->length(14)->nullable();
			$table->string('NOMEADQUIRENTE')->length(40)->nullable();
			$table->float('VLRSACADOLAR')->nullable();
			$table->integer('NUMCOO')->nullable();
			$table->integer('ORDEMCARGAANT')->nullable();
			$table->string('TPAMBNFE')->length(1)->nullable();
			$table->integer('PRZMED')->nullable();
			$table->integer('CODRESIDUO')->nullable();
			$table->date('DTREF2')->nullable();
			$table->string('VLRLIQITEMNFE')->length(1)->nullable();
			$table->string('CLASCONS')->length(2)->nullable();
			$table->integer('NUMFORM')->nullable();
			$table->date('DTREF3')->nullable();
			$table->integer('CODCC')->nullable();
			$table->string('PRODUETLOC')->length(1)->nullable();
			$table->float('VLRSTEXTRANOTATOT')->nullable();
			$table->integer('NUTRANEMP')->nullable();
			$table->string('SITESPECIALRESP')->length(2)->nullable();
			$table->date('DTENTSAIINFO')->nullable();
			$table->string('EXIGEISSQN')->length(2)->nullable();
			$table->string('REGESPTRIBUT')->length(2)->nullable();
			$table->string('MOTNAORETERISSQN')->length(2)->nullable();
			$table->date('DTREMRET')->nullable();
			$table->string('LIBCONF')->length(1)->nullable();
			$table->integer('NUCONFATUAL')->nullable();
			$table->string('STATUSXTRATEGIE')->length(1)->nullable();
			$table->integer('CODSAF')->nullable();
			$table->float('VLRFRETECALC')->nullable();
			$table->float('VLRJURODIST')->nullable();
			$table->string('NOTAEMPENHO')->length(22)->nullable();
			$table->string('PESOBRUTOMANUAL')->length(1)->nullable();
			$table->string('PESOLIQUIMANUAL')->length(1)->nullable();
			$table->string('CANCELADO')->length(1)->nullable();
			$table->integer('CODTPD')->nullable();
			$table->integer('CODVTP')->nullable();
			$table->integer('NUPCA')->nullable();
			$table->string('INDPRESNFCE')->length(1)->nullable();
			$table->float('M3')->nullable();
			$table->float('VLRTOTLIQITEMMOE');
			$table->float('VLRDESCTOTITEMMOE');
			$table->string('CHAVECTE')->length(44)->nullable();
			$table->string('PRODPRED')->length(60)->nullable();
			$table->integer('TPEMISCTE')->nullable();
			$table->string('TPAMBCTE')->length(1)->nullable();
			$table->string('LOTACAO')->length(1)->nullable();
			$table->string('STATUSCTE')->length(1)->nullable();
			$table->integer('NUMALEATORIOCTE')->nullable();
			$table->string('NUMPROTOCCTE')->length(30)->nullable();
			$table->date('DHPROTOCCTE')->nullable();
			$table->integer('NULOTECTE')->nullable();
			$table->date('DTDECLARA')->nullable();
			$table->integer('REBOQUE1')->nullable();
			$table->integer('REBOQUE2')->nullable();
			$table->integer('REBOQUE3')->nullable();
			$table->string('SITUACAOCTE')->length(1)->nullable();
			$table->string('CTELOTACAO')->length(1)->nullable();
			$table->integer('CODVEITRACAO')->nullable();
			$table->string('CODOBRA')->length(15)->nullable();
			$table->string('CODART')->length(15)->nullable();
			$table->integer('IDIPROC')->nullable();
			$table->string('VIATRANSP')->length(2)->nullable();
			$table->string('TIPPROCIMP')->length(1)->nullable();
			$table->string('CNPJADQUIRENTE')->length(14)->nullable();
			$table->string('UFADQUIRENTE')->length(2)->nullable();
			$table->integer('NUNOTASUB')->nullable();
			$table->string('CHAVENFSE')->length(44)->nullable();
			$table->date('DHEMISSEPEC')->nullable();
			$table->string('MODENTREGA')->length(1)->nullable();
			$table->float('VLRICMSDIFALDEST')->nullable();
			$table->float('VLRICMSDIFALREM')->nullable();
			$table->integer('CIOT')->nullable();
			$table->float('VLRICMSFCP')->nullable();
			$table->float('VLRFRETETOTAL')->nullable();
			$table->integer('CODPARCTRANSPFINAL')->nullable();
			$table->string('FUSOEMISSEPEC')->length(6)->nullable();
			$table->string('CHAVENFEREF')->length(44)->nullable();
			$table->float('VLRDESCRAT')->nullable();
			$table->integer('SEQCONFIRMA')->nullable();
			$table->integer('CODCONTATOENTREGA')->nullable();
			$table->integer('CODCIDORIGEM')->nullable();
			$table->integer('CODCIDDESTINO')->nullable();
			$table->integer('CODCIDENTREGA')->nullable();
			$table->integer('CODUFORIGEM')->nullable();
			$table->integer('CODUFDESTINO')->nullable();
			$table->integer('CODUFENTREGA')->nullable();
			$table->string('CLASSIFICMS')->length(1)->nullable();
			$table->integer('NUFOP')->nullable();
			$table->string('CODRASTREAMENTOECT')->length(30)->nullable();
			$table->integer('NUODP')->nullable();
			$table->integer('NUPEDFRETE')->nullable();
			$table->integer('CODCIDPREST')->nullable();
			$table->string('FORMPGTCTE')->length(1)->nullable();
			$table->float('PERCDESCFOB')->nullable();
			$table->string('TPAMBNFSE')->length(1)->nullable();
			$table->string('TERMACORDNOTA')->length(1)->nullable();
			$table->float('VLRDESCQTD')->nullable();
			$table->float('VLRICMSFCPINT')->nullable();
			$table->float('VLRSTFCPINT')->nullable();
			$table->float('VLRSTFCPINTANT')->nullable();
			$table->string('CTEGLOBAL')->length(1)->nullable();
			$table->float('VLRCARGAAVERB')->nullable();
			$table->integer('CODCIDINICTE')->nullable();
			$table->integer('CODCIDFIMCTE')->nullable();
			$table->integer('NUCFR')->nullable();
			$table->string('NFEDEVRECUSA')->length(1)->nullable();
			$table->string('AGRUPFINNOTA')->length(1)->nullable();
			$table->float('VLRPRESTAFRMM')->nullable();
			$table->float('VLRAFRMM')->nullable();
			$table->string('IDNAVIO')->length(60)->nullable();
			$table->string('IRINNAVIO')->length(10)->nullable();
			$table->string('DIRECAOVIAG')->length(1)->nullable();
			$table->string('IDBALSA01')->length(60)->nullable();
			$table->string('IDBALSA02')->length(60)->nullable();
			$table->string('IDBALSA03')->length(60)->nullable();
			$table->string('CONFIRMNOTAFAT')->length(1)->nullable();
			$table->string('PERMALTERCENTRAL')->length(60)->nullable();
			$table->integer('CODGUF')->nullable();
			$table->string('FINALIZADOFOX')->length(1)->nullable();
			$table->float('VLRREPREDTOTSEMDESC')->nullable();
			$table->integer('NUMCUPOMECONECT')->nullable();
			$table->integer('TIMNUFINORIG')->nullable();
			$table->integer('TIMCONTRATOVENDA')->nullable();
			$table->string('TIMORIGEM')->length(2)->nullable();
			$table->integer('TIMCONTRATOLTV')->nullable();
			$table->integer('TIMNUNOTAMOD')->nullable();
			$table->date('DTEXTEMPK280')->nullable();
			$table->string('LATITUDE')->length(255)->nullable();
			$table->string('LONGITUDE')->length(255)->nullable();
			$table->integer('CODPARCDESCARGAMDFE')->nullable();
			$table->integer('CODDOCARRECAD')->nullable();
			$table->string('NUMDOCARRECAD')->length(30)->nullable();
			$table->string('PREMIACAOESTADUAL')->length(255)->nullable();
			$table->string('NFSEID')->length(50)->nullable();
			$table->integer('CODPARCDEPO')->nullable();
			$table->float('VLRFETHAB')->nullable();
			$table->integer('CODCHECKOUT')->nullable();
			$table->float('BASEICMSAT')->nullable();
			$table->float('VLRICMSAT')->nullable();
			$table->string('DISDESAUTIMPEMB')->length(1)->nullable();
			$table->integer('IDDESCPARCERIA')->nullable();
			$table->integer('VLRDESCPARCERIA')->nullable();
			$table->integer('CLIENTEIDPARCERIA')->nullable();
			$table->integer('IDPONTUACAOPARCERIA')->nullable();
			$table->float('VALORDESONPISCOFINS')->nullable();
			$table->integer('NUNOTAORIGCORTE')->nullable();
			$table->float('BASEICMSSTFRETE')->nullable();
			$table->float('ICMSSTFRETE')->nullable();
			$table->float('VLRREPREDST')->nullable();
			$table->integer('CODINTERM')->nullable();
			$table->string('INTERMED')->length(1)->nullable();
			$table->string('FISTEL')->length(11)->nullable();
			$table->integer('NUMCSTC')->nullable();
			$table->integer('QTDUSU')->nullable();
			$table->integer('NUMTERMTEL')->nullable();
			$table->integer('TIPCLIENTESERVCOM')->nullable();
			$table->string('MD5MODCOMTEL')->length(32)->nullable();
			$table->string('INDNEGMODAL')->length(1)->nullable();
			$table->integer('CODPARCRETIRADA')->nullable();
			$table->string('NOTAPORPEDIDOPDV')->length(1)->default('N' );
			$table->integer('SUMVLRIIOUTNOTA')->nullable();
			$table->integer('SOMICMSNFENAC')->nullable();
			$table->integer('SOMPISCOFNFENAC')->nullable();
			$table->string('STATUSCFE')->length(1)->nullable();
			$table->float('AD_VLRCOMISSAOPARCEIRO')->nullable();
			$table->string('AD_PROFORMA')->length(100)->nullable();
			$table->string('AD_INCONTERMS')->length(10)->nullable();
			$table->integer('AD_NUMMERCOS')->nullable();
			$table->string('RETORNOEQUIPFISCAL')->length(255)->nullable();
			$table->string('AD_OBSERVACAO_INTERNA')->length(4000)->nullable();
			$table->string('AD_NOTAREFERENCIA')->length(100)->nullable();
			$table->integer('NUNOTAREC')->nullable();
			$table->string('RETGERWMS')->length(1)->nullable();
			$table->integer('NURECEBIMENTO')->nullable();
			$table->date('DHVIAGEM')->nullable();
			$table->integer('NUSESSAO')->nullable();
			$table->integer('TPFRETAMENTO')->nullable();
			$table->string('DESCRNAT')->length(40);
			$table->string('INCRESULT')->length(1)->default('S' );
			$table->integer('CODCTACTB')->nullable();
			$table->integer('CODCENCUS')->nullable();
			$table->integer('CODNATPAI')->nullable();
			$table->integer('GRAU')->nullable();
			$table->string('ATIVA')->length(1)->default('S' );
			$table->string('ANALITICA')->length(1)->default('S' );
			$table->integer('CODCTACTB2')->nullable();
			$table->integer('CODHISTCTB')->nullable();
			$table->integer('CODHISTCTB2')->nullable();
			$table->string('GRUPOMKP')->length(30)->nullable();
			$table->string('SUBGRUPOMKP')->length(30)->nullable();
			$table->integer('DECVLR')->nullable();
			$table->string('FORMULA')->length(4000)->nullable();
			$table->integer('CSTPIS')->nullable();
			$table->integer('CSTCOFINS')->nullable();
			$table->string('NATBCCRED')->length(2)->nullable();
			$table->float('ALIQPIS')->nullable();
			$table->float('ALIQCOFINS')->nullable();
			$table->integer('CODPROD')->nullable();
			$table->integer('CODSERVUNICO')->nullable();
			$table->string('REGIMEEFD')->length(1)->default('A' );
			$table->integer('CODGRUPONAT');
			$table->string('TIPNAT')->length(1)->nullable();
			$table->string('FINREGP100')->length(1)->default('N' );
			$table->string('FINCODATIVP100')->length(8)->nullable();
			$table->integer('CODCTACTBEFD')->nullable();
			$table->string('GERALCDPR')->length(1)->nullable();
			$table->string('RECADIANTRURAL')->length(1)->nullable();
			$table->integer('NATEFDCONTM410M810')->nullable();
			$table->string('AD_IMPLIGACAO')->length(10)->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->float('RESERVADO')->nullable();
			$table->float('ESTMIN');
			$table->float('ESTMAX');
			$table->string('ATIVO')->length(1)->default('S' );
			$table->string('CODBARRA')->length(25)->nullable();
			$table->date('DTVAL')->nullable();
			$table->float('PERCPUREZA')->nullable();
			$table->float('PERCGERMIN')->nullable();
			$table->float('ESTOQUE');
			$table->date('DTFABRICACAO')->nullable();
			$table->string('STATUSLOTE')->length(1)->default('N' );
			$table->string('MD5PAF')->length(32)->nullable();
			$table->date('DTENTRADA')->nullable();
			$table->float('QTDPEDPENDEST')->nullable();
			$table->float('WMSBLOQUEADO')->nullable();
			$table->float('PERCVC')->nullable();
			$table->string('CODAGREGACAO')->length(20)->nullable();
			$table->integer('CODVEND');
			$table->string('NOMEPARC')->length(80);
			$table->string('RAZAOSOCIAL')->length(80)->nullable();
			$table->string('TIPPESSOA')->length(1);
			$table->integer('CODPARCMATRIZ')->nullable();
			$table->integer('CODEND');
			$table->string('NUMEND')->length(6)->nullable();
			$table->string('COMPLEMENTO')->length(30)->nullable();
			$table->integer('CODBAI');
			$table->integer('CODCID');
			$table->integer('CODREG');
			$table->string('CEP')->length(8)->nullable();
			$table->string('CAIXAPOSTAL')->length(10)->nullable();
			$table->string('TELEFONE')->length(13)->nullable();
			$table->integer('RAMAL')->nullable();
			$table->string('FAX')->length(13)->nullable();
			$table->string('EMAIL')->length(80)->nullable();
			$table->date('DTCAD');
			$table->date('DTALTER');
			$table->date('DTNASC')->nullable();
			$table->date('DTULTCONTATO')->nullable();
			$table->date('DTULTNEGOC')->nullable();
			$table->string('IDENTINSCESTAD')->length(16)->nullable();
			$table->string('INSCESTADNAUF')->length(16)->nullable();
			$table->string('CGC_CPF')->length(14)->nullable();
			$table->integer('CODTAB')->nullable();
			$table->integer('PRAZOCONTATO')->nullable();
			$table->integer('PRAZOPAG')->nullable();
			$table->integer('TOLERINADIMP')->nullable();
			$table->string('CLIENTE')->length(1)->default('S' );
			$table->string('FORNECEDOR')->length(1)->default('N' );
			$table->string('TRANSPORTADORA')->length(1)->default('N' );
			$table->string('VENDEDOR')->length(1)->default('N' );
			$table->string('AGENCIA')->length(1)->default('N' );
			$table->integer('CODTIPPARC');
			$table->string('CODCTABCO')->length(17)->nullable();
			$table->string('CODAGE')->length(5)->nullable();
			$table->integer('CODBCO');
			$table->string('NOMEAGE')->length(19)->nullable();
			$table->integer('CODCTACTB')->nullable();
			$table->integer('CODCTACTB2')->nullable();
			$table->string('CLASSIFICMS')->length(1)->nullable();
			$table->string('TARE')->length(1)->default('N' );
			$table->string('IPIINCICMS')->length(1)->default('N' );
			$table->string('RETEMISS')->length(1)->default('N' );
			$table->string('RETEMINSS')->length(1)->default('N' );
			$table->string('CONTACESSO')->length(30)->nullable();
			$table->string('SITUACAO')->length(1)->nullable()->default('B');
			$table->string('OBSERVACOES')->length(4000)->nullable();
			$table->string('ATIVO')->length(1)->default('S' );
			$table->integer('CODANT')->nullable();
			$table->integer('CODCTABCOINT')->nullable();
			$table->string('GRUPOAUTOR')->length(30)->nullable();
			$table->float('LIMCRED')->nullable();
			$table->string('BLOQUEAR')->length(1)->default('N' );
			$table->string('SELECIONADO')->length(1)->nullable();
			$table->string('MOTBLOQ')->length(4000)->nullable();
			$table->string('EVENDA')->length(1)->default('N' );
			$table->string('ECOMPRA')->length(1)->default('N' );
			$table->string('HOMEPAGE')->length(255)->nullable();
			$table->string('CTAADIANT')->length(1)->default('N' );
			$table->integer('CODASSESSOR');
			$table->string('INSCMUN')->length(16)->nullable();
			$table->string('CALCINSS')->length(1)->default('N' );
			$table->integer('CODUSU');
			$table->string('RETEMPIS')->length(1)->default('N' );
			$table->string('RETEMCOFINS')->length(1)->default('N' );
			$table->string('RETEMCSL')->length(1)->default('N' );
			$table->string('USUARIO')->length(1)->nullable()->default('N');
			$table->string('CEI')->length(12)->nullable();
			$table->float('LIMCREDMENSAL')->nullable();
			$table->integer('CODTABST')->nullable();
			$table->integer('QTDMAXTITVENCIDOS')->nullable();
			$table->string('TEMIPI')->length(1)->default('S' );
			$table->string('ALUNO')->length(1)->nullable();
			$table->string('PROFESSOR')->length(1)->nullable();
			$table->float('DESCFIN')->nullable();
			$table->string('DESCBONIF')->length(1)->default('L' );
			$table->string('IMPLAUDOLOTE')->length(1)->default('N' );
			$table->integer('DIASEM')->nullable();
			$table->string('MEDICO')->length(1)->default('N' );
			$table->string('TIPOFATUR')->length(1)->default('L' );
			$table->integer('DIASVARPAGTO')->nullable();
			$table->string('CODUNIMED')->length(17)->nullable();
			$table->integer('CODCRED')->nullable();
			$table->float('PERCCUSVAR')->nullable();
			$table->string('MOTORISTA')->length(1)->default('N' );
			$table->string('NATUREZAOPERDES')->length(2)->nullable();
			$table->string('SERIENFDES')->length(4)->nullable();
			$table->string('MODELONFDES')->length(2)->nullable();
			$table->string('DESCSTIVA')->length(1)->default('S' );
			$table->integer('CSTIPIENT')->nullable();
			$table->integer('CSTIPISAI')->nullable();
			$table->integer('CODEMP')->nullable();
			$table->float('VLRMINPEDCPA')->nullable();
			$table->integer('QTDMAXPEDCPA')->nullable();
			$table->string('OPERLOGIST')->length(1)->default('N' );
			$table->string('AGRONOMO')->length(1)->default('N' );
			$table->string('PRODUTORTEMNF')->length(1)->default('S' );
			$table->float('POTENCIALNEG')->nullable();
			$table->string('EMAILNFE')->length(255)->nullable();
			$table->string('TIPANEXONFE')->length(1)->default('X' );
			$table->string('ORDSUBST')->length(1)->nullable();
			$table->float('MAXCREDINDENIZ')->nullable();
			$table->float('MAXDEBINDENIZ')->nullable();
			$table->float('SALDOINDENIZ')->nullable();
			$table->string('FLEX')->length(1)->default('S' );
			$table->string('SIMPLES')->length(1)->default('N' );
			$table->string('SEXO')->length(1)->nullable();
			$table->integer('NURESPPERG')->nullable();
			$table->integer('NURESPPERGFECH')->nullable();
			$table->integer('CODROTA')->nullable();
			$table->integer('CODCTACTB3')->nullable();
			$table->integer('CODCTACTB4')->nullable();
			$table->integer('CODUSUCOBR');
			$table->string('AGRUPAR')->length(1)->nullable();
			$table->string('EMAILDANFE')->length(1)->default('N' );
			$table->string('VALDESCGRDCAR')->length(1)->nullable();
			$table->string('AGRUPBOLEMPDIF')->length(1)->nullable();
			$table->float('PERCREDINSS')->nullable();
			$table->string('PERMITECORTE')->length(1)->default('S' );
			$table->string('INDNATRET')->length(2)->nullable();
			$table->string('STATUSEDZ')->length(1)->default('P' );
			$table->string('SITRECEITA')->length(1)->default('I' );
			$table->string('SITSINTEGRA')->length(1)->default('I' );
			$table->string('SITCCF')->length(1)->default('I' );
			$table->string('USATABCRFORN')->length(1)->default('N' );
			$table->integer('QTDPEDPRZMED')->nullable();
			$table->integer('DIASPEDPRZMED')->nullable();
			$table->string('ARTPRECAD')->length(1)->default('N' );
			$table->string('GERCTRCAUTO')->length(1)->default('N' );
			$table->integer('CODLOCALPADRAO');
			$table->float('SALDODISP')->nullable();
			$table->float('PROVACRESC')->nullable();
			$table->string('EXIGELAUDOPRD')->length(1)->nullable();
			$table->string('MEIRJ')->length(1)->nullable();
			$table->string('ENTREGAENDCONTATO')->length(1)->default('N' );
			$table->integer('CODEMPPARC')->nullable();
			$table->string('RETSTVENDA')->length(1)->default('N' );
			$table->string('LATITUDE')->length(255)->nullable();
			$table->string('LONGITUDE')->length(255)->nullable();
			$table->string('TIPOGERBOLETO')->length(1)->default('I' );
			$table->float('PERCJURO')->nullable();
			$table->float('PERCMULTA')->nullable();
			$table->string('TIPJURO')->length(1)->nullable();
			$table->float('PERCDESCESPECIAL')->nullable();
			$table->integer('CODEMPPREF')->nullable();
			$table->string('SITESPECIALRESP')->length(2)->nullable();
			$table->string('MOTNAORETERISSQN')->length(2)->nullable();
			$table->integer('SITCADSEFAZ')->nullable();
			$table->date('DHCADSEFAZ')->nullable();
			$table->float('ALIQISSRETSIMPLES')->nullable();
			$table->string('IDESTRANGEIRO')->length(20)->nullable();
			$table->string('TIPGERBOLCENT')->length(1)->nullable();
			$table->string('COMOCONHECEU')->length(100)->nullable();
			$table->string('TIPOGERBOLETODUP')->length(1)->default('I' );
			$table->string('BOLDESTEMAIL')->length(1)->default('A' );
			$table->integer('TPASSINANTE')->nullable();
			$table->string('APLICLEITRANSP')->length(1)->default('N' );
			$table->float('VENDAMIN')->nullable();
			$table->integer('CODENQIPIENT')->nullable();
			$table->integer('CODENQIPISAI')->nullable();
			$table->string('ENVIPEDEMAILTOP')->length(1)->default('A' );
			$table->string('INTEGRAECONECT')->length(1)->default('N' );
			$table->string('SENHAECONECT')->length(32)->nullable();
			$table->string('PRAZOPARCECONECT')->length(32)->nullable();
			$table->integer('BASEPRAZOECONECT');
			$table->string('PARCELAMECONECT')->length(32)->nullable();
			$table->integer('BASEPARCELECONECT');
			$table->integer('DIAFECHAECONECT')->nullable();
			$table->integer('DIAPAGTOECONECT')->nullable();
			$table->string('PERFILECONECT')->length(1)->default('B' );
			$table->date('DTEMISNFEFORN')->nullable();
			$table->string('ESTABTRANSP')->length(1)->nullable();
			$table->string('TRANSPPROPRIA')->length(1)->nullable();
			$table->string('TERMACORD')->length(1)->nullable()->default('N');
			$table->integer('INTERVANALISCRED')->nullable();
			$table->string('INDCOMERCIALIZACAO')->length(5)->nullable();
			$table->string('INDAQUISICAO')->length(5)->nullable();
			$table->float('MERCHANTID')->nullable();
			$table->string('EMAILNOTIFENTREGA')->length(80)->nullable();
			$table->string('IMPAGRUPFIN')->length(1)->nullable();
			$table->integer('TIPLOTACAO')->nullable();
			$table->integer('UNIDIMPORT')->nullable();
			$table->integer('CODPARCGRUECONOMICO')->nullable();
			$table->string('ENQART227')->length(1)->nullable();
			$table->float('LIMCHEQECONECT')->nullable();
			$table->string('ORGPUBLNFSE')->length(1)->nullable();
			$table->string('ASSOCIACAODESP')->length(1)->nullable();
			$table->integer('MODELONOTACOMPRA')->nullable();
			$table->string('ARREDPRIMEIRAPARC')->length(1)->nullable();
			$table->integer('SITCADRF')->nullable();
			$table->date('DHCADRF')->nullable();
			$table->string('VLRLIQITEMNFE')->length(1)->nullable();
			$table->string('VLRLIQITEMNFCE')->length(1)->nullable();
			$table->string('CPFPRODRURAL')->length(11)->nullable();
			$table->string('EMAILNFSE')->length(255)->nullable();
			$table->integer('NUFOP')->nullable();
			$table->string('CNAE')->length(10)->nullable();
			$table->integer('INDCREDNFE')->nullable();
			$table->integer('INDCREDCTE')->nullable();
			$table->date('DTINIATIV')->nullable();
			$table->date('DTULTSIT')->nullable();
			$table->date('DTBAIXA')->nullable();
			$table->string('REGAPUR')->length(50)->nullable();
			$table->integer('CODGRUPO')->nullable();
			$table->string('PARCINTER')->length(1)->nullable();
			$table->integer('INDOPCCP')->nullable();
			$table->string('TRUNCPARCELA')->length(1)->nullable();
			$table->integer('NUVERSAO')->nullable();
			$table->integer('CODCONTATOPADCOT')->nullable();
			$table->string('TIMESTADOCIVIL')->length(2)->nullable()->default('NI');
			$table->string('TIMQUERCOMPRAR')->length(1)->nullable()->default('N');
			$table->string('TIMREFERENCIA02')->length(40)->nullable();
			$table->string('TIMORGAO')->length(10)->nullable();
			$table->string('TIMCOMPRADOR')->length(1)->nullable()->default('N');
			$table->integer('TIMBAIRROCOMPRA')->nullable();
			$table->date('TIMDATACI')->nullable();
			$table->string('TIMPROPVENDA')->length(1)->nullable()->default('N');
			$table->string('TIMPAI')->length(50)->nullable();
			$table->string('TIMREFERENCIA01')->length(40)->nullable();
			$table->string('TIMTIPOMORADIA')->length(2)->nullable();
			$table->string('TIMINQUILINO')->length(1)->nullable()->default('N');
			$table->string('TIMTELEFONE02')->length(30)->nullable();
			$table->string('TIMPROPRIETA')->length(1)->nullable()->default('N');
			$table->string('TIMCORRESPBANCARIO')->length(1)->nullable()->default('N');
			$table->string('TIMMAE')->length(50)->nullable();
			$table->string('TIMFAIXASALARIAL')->length(10)->nullable()->default('NI');
			$table->string('TIMCORRETOR')->length(1)->nullable()->default('N');
			$table->string('TIMOUTTELS')->length(400)->nullable();
			$table->string('TIMTELEFONE01')->length(40)->nullable();
			$table->integer('TIMAINVESTIR')->nullable();
			$table->string('TIMFIADOR')->length(1)->nullable()->default('N');
			$table->string('TIMSENHASITE')->length(8)->nullable()->default('--');
			$table->string('TIMSENHADESC')->length(8)->nullable()->default('--');
			$table->integer('TIMCARTORIO')->nullable();
			$table->integer('TIMPROFISSAO')->nullable();
			$table->integer('TIMNACIONALIDAD')->nullable();
			$table->string('TIMCARTREGIMEBENSV')->length(3)->nullable();
			$table->string('INSCRCNO')->length(12)->nullable();
			$table->string('PARCSUBSTISS')->length(1)->nullable();
			$table->string('EXIGCONTATOENTCAB')->length(1)->nullable();
			$table->string('ENVIADANFEREDESPACHO')->length(1)->nullable();
			$table->string('EXIGENOMEPARC')->length(1)->nullable();
			$table->float('SALDODISPCAC')->nullable();
			$table->float('PROVACRESCCAC')->nullable();
			$table->string('CONSIDTOTITENSTRIB')->length(1)->nullable();
			$table->string('ATUNUVERSAO')->length(1)->nullable();
			$table->string('DESCONSIDESCBASE')->length(1)->nullable();
			$table->integer('CODIDENTCONS')->nullable();
			$table->string('UTILIZANUCADPARC')->length(1)->nullable();
			$table->integer('TIPCLIENTESERVCOM')->nullable();
			$table->string('CHAVEPIX')->length(77)->nullable();
			$table->string('EMAILCTE')->length(255)->nullable();
			$table->string('CONSPARCADRCST')->length(1)->nullable();
			$table->string('DESCONSDESCINSS')->length(1)->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->float('AD_COMISSAO')->nullable();
			$table->integer('NUTAB')->nullable();
			$table->integer('CODEMP');
			$table->integer('CODPROD');
			$table->integer('CODLOCALORIG');
			$table->string('CONTROLE')->length(19)->default(' ' );
			$table->string('USOPROD')->length(1)->default('V' );
			$table->integer('CODCFO');
			$table->float('QTDNEG');
			$table->float('QTDENTREGUE');
			$table->float('QTDCONFERIDA');
			$table->float('VLRUNIT');
			$table->float('VLRTOT');
			$table->float('VLRCUS');
			$table->float('BASEIPI');
			$table->float('VLRIPI');
			$table->float('BASEICMS');
			$table->float('VLRICMS');
			$table->float('VLRDESC');
			$table->float('BASESUBSTIT');
			$table->float('VLRSUBST');
			$table->float('ALIQICMS')->nullable();
			$table->float('ALIQIPI')->nullable();
			$table->string('PENDENTE')->length(1)->default('S' );
			$table->string('CODVOL')->length(2)->default('0' );
			$table->integer('CODTRIB')->nullable();
			$table->integer('ATUALESTOQUE')->default(-1);
			$table->string('OBSERVACAO')->length(4000)->nullable();
			$table->string('RESERVA')->length(1)->default('N' );
			$table->string('STATUSNOTA')->length(1)->default('P' );
			$table->integer('CODOBSPADRAO')->nullable();
			$table->integer('CODVEND');
			$table->integer('CODEXEC');
			$table->string('FATURAR')->length(1)->default('S' );
			$table->float('VLRREPRED');
			$table->float('VLRDESCBONIF');
			$table->float('PERCDESC');
			$table->float('M3')->nullable();
			$table->float('ALIQICMSRED')->nullable();
			$table->integer('CODPARCEXEC')->nullable();
			$table->float('CUSTO')->nullable();
			$table->float('BASESUBSTSEMRED')->nullable();
			$table->integer('CODUSU')->nullable();
			$table->date('DTALTER')->nullable();
			$table->string('SOLCOMPRA')->length(1)->nullable();
			$table->integer('CODTRIBISS')->nullable();
			$table->integer('CODCFPS')->nullable();
			$table->float('ALIQISS')->nullable();
			$table->float('QTDFORMULA')->nullable();
			$table->string('ATUALESTTERC')->length(1)->nullable();
			$table->float('PERCDESCBONIF')->nullable();
			$table->string('TERCEIROS')->length(1)->nullable();
			$table->string('ENDIMAGEM')->length(100)->nullable();
			$table->float('ALTURA')->nullable();
			$table->float('LARGURA')->nullable();
			$table->float('ESPESSURA')->nullable();
			$table->integer('CODCAV')->nullable();
			$table->integer('CODPROC')->nullable();
			$table->float('QTDPECA')->nullable();
			$table->float('PRECOBASE')->nullable();
			$table->float('VLRACRESCDESC')->nullable();
			$table->float('VLRRETENCAO')->nullable();
			$table->integer('CSTIPI')->nullable();
			$table->float('PERCCOM')->nullable();
			$table->float('VLRCOM')->nullable();
			$table->string('ALTPRECO')->length(1)->nullable();
			$table->float('QTDFIXADA')->nullable();
			$table->float('PERCCOMGER')->nullable();
			$table->float('VLRCOMGER')->nullable();
			$table->float('QTDWMS')->nullable();
			$table->integer('BASICMMOD')->nullable();
			$table->integer('BASICMSTMOD')->nullable();
			$table->float('QTDFAT')->nullable();
			$table->float('BASESTUFDEST')->nullable();
			$table->float('VLRICMSUFDEST')->nullable();
			$table->float('BASESTANT')->nullable();
			$table->integer('GRUPOTRANSG')->nullable();
			$table->string('PRODUTONFE')->length(60)->nullable();
			$table->string('GTINNFE')->length(14)->nullable();
			$table->string('GTINTRIBNFE')->length(14)->nullable();
			$table->integer('CODPROMO')->nullable();
			$table->float('VLRPROMO')->nullable();
			$table->float('VLRLIQPROM')->nullable();
			$table->float('PRECOBASEQTD')->nullable();
			$table->string('RETDATACRITICA')->length(1)->nullable();
			$table->float('PERCPUREZA')->nullable();
			$table->float('PERCGERMIN')->nullable();
			$table->integer('NUPROMOCAO')->nullable();
			$table->float('PERCDESCPROM')->nullable();
			$table->float('VLRPTOPUREZA')->nullable();
			$table->string('CODANTECIPST')->length(1)->nullable();
			$table->integer('NUMPEDIDO')->nullable();
			$table->integer('SEQPEDIDO')->nullable();
			$table->integer('CSOSN')->nullable();
			$table->string('NUMPEDIDO2')->length(15)->nullable();
			$table->string('SEQPEDIDO2')->length(6)->nullable();
			$table->string('STATUSLOTE')->length(1)->nullable();
			$table->integer('QTDVOL')->nullable();
			$table->string('SERIEINICIAL')->length(30)->nullable();
			$table->string('SERIEFINAL')->length(30)->nullable();
			$table->date('DTINICIO')->nullable();
			$table->integer('HRINICIO')->nullable();
			$table->integer('HRFIM')->nullable();
			$table->float('VLRUNITDOLAR')->nullable();
			$table->float('PESO')->nullable();
			$table->string('MD5PAF')->length(32)->nullable();
			$table->float('BASEISS')->nullable();
			$table->float('VLRISS')->nullable();
			$table->integer('CODTPA')->nullable();
			$table->float('VLRTROCA')->nullable();
			$table->integer('VARIACAOFCP')->nullable();
			$table->date('DTFIM')->nullable();
			$table->integer('TEMPOGASTO')->nullable();
			$table->float('DESVIOPADRAO')->nullable();
			$table->integer('PERCTROCA')->nullable();
			$table->float('PERCDESCDIGITADO')->nullable();
			$table->float('PERCDESCTGFDES')->nullable();
			$table->integer('SEQUENCIAFISCAL')->nullable();
			$table->float('VLRDESCDIGITADO')->nullable();
			$table->float('PERCVC')->nullable();
			$table->integer('CODMOTDESONERAICMS')->nullable();
			$table->integer('CODETAPA')->nullable();
			$table->integer('VARIACAO')->nullable();
			$table->string('ATUALESTINDIVIDUAL')->length(1)->nullable();
			$table->float('VLRSTEXTRANOTA')->nullable();
			$table->string('ULOCETPAESTIND')->length(1)->nullable();
			$table->integer('CODLOCALTERC')->nullable();
			$table->string('ORIGPROD')->length(1)->nullable();
			$table->float('PERCDESCBASE')->nullable();
			$table->string('NRSERIERESERVA')->length(60)->nullable();
			$table->float('VLRUNITLOC')->nullable();
			$table->float('VLRICMSANT')->nullable();
			$table->float('BASESUBSTITANT')->nullable();
			$table->float('VLRSUBSTANT')->nullable();
			$table->integer('NUMEROOS')->nullable();
			$table->string('CANCELADO')->length(1)->nullable();
			$table->integer('GRUPOFAT')->nullable();
			$table->integer('NUMCONTRATO')->nullable();
			$table->integer('IDALIQICMS')->nullable();
			$table->float('VLRUNITMOE');
			$table->float('VLRDESCMOE');
			$table->float('VLRTOTMOE');
			$table->string('CODVOLPARC')->length(6)->nullable();
			$table->integer('CODENQIPI')->nullable();
			$table->integer('CODESPECST')->nullable();
			$table->float('VLRDESCRAT')->nullable();
			$table->integer('NUFOP')->nullable();
			$table->float('BASESUBSTITUNITORIG')->nullable();
			$table->float('VLRSUBSTUNITORIG')->nullable();
			$table->string('GERAPRODUCAO')->length(1)->default('S' );
			$table->string('CODAGREGACAO')->length(20)->nullable();
			$table->string('INDESCALA')->length(1)->nullable();
			$table->string('CNPJFABRICANTE')->length(14)->nullable();
			$table->float('BASESTFCPINTANT')->nullable();
			$table->float('VLRSTFCPINTANT')->nullable();
			$table->float('PERCSTFCPINTANT')->nullable();
			$table->string('CODBENEFNAUF')->length(10)->nullable();
			$table->float('PERCDESCFORNECEDOR')->nullable();
			$table->string('ORIGEMBUSCA')->length(18)->nullable();
			$table->integer('PRODUTOPESQUISADO')->nullable();
			$table->float('ALIQSTEXTRANOTA')->nullable();
			$table->float('BASESTEXTRANOTA')->nullable();
			$table->float('QTDTRIBEXPORT')->nullable();
			$table->string('CODPROINFO')->length(32)->nullable();
			$table->float('ALIQSTFCPSTANT')->nullable();
			$table->float('VLRVENDAPROMO')->nullable();
			$table->float('VLRREPREDSEMDESC')->nullable();
			$table->integer('CODDOCARRECAD')->nullable();
			$table->string('NUMDOCARRECAD')->length(30)->nullable();
			$table->float('VLRICMSDIFERIDO')->nullable();
			$table->string('TIPOSEPARACAO')->length(1)->nullable();
			$table->float('BASECALCSTEXTRANOTA')->nullable();
			$table->float('REDBASEST')->nullable();
			$table->float('MARGLUCRO')->nullable();
			$table->float('PERCREDVLRIPI')->nullable();
			$table->integer('IDALIQICMSDIFICMS')->nullable();
			$table->string('TIPENTREGA')->length(1)->nullable();
			$table->float('ALIQFETHAB')->nullable();
			$table->float('VLRFETHAB')->nullable();
			$table->integer('IDALIQICMSAT')->nullable();
			$table->float('BASEICMSAT')->nullable();
			$table->float('ALIQICMSAT')->nullable();
			$table->float('ALIQINTERICMSAT')->nullable();
			$table->float('VLRICMSAT')->nullable();
			$table->integer('IDDESCPARCERIA')->nullable();
			$table->integer('VLRDESCPARCERIA')->nullable();
			$table->float('PERCUSAQUDECPE')->nullable();
			$table->float('VLRCUSAQUDECPE')->nullable();
			$table->float('BASEICMSSTFRETE')->nullable();
			$table->float('ICMSSTFRETE')->nullable();
			$table->float('VLRREPREDST')->nullable();
			$table->string('CODSIT08EFD')->length(1)->nullable();
			$table->integer('TIPUTILCOM')->nullable();
			$table->string('UNIDADE')->length(6)->nullable();
			$table->float('ALIQFUST')->nullable();
			$table->float('BASEFUST')->nullable();
			$table->float('VLRFUST')->nullable();
			$table->float('ALIQFUNTTEL')->nullable();
			$table->float('BASEFUNTTEL')->nullable();
			$table->float('VLRFUNTTEL')->nullable();
			$table->integer('CODMOTDESONERAST')->nullable();
			$table->string('CODBARRAPDV')->length(25)->nullable();
			$table->string('CODFCI')->length(36)->nullable();
			$table->float('PERCUSAQUDECPEEST')->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->string('AD_LOTEREFERENCIA')->length(100)->nullable();
			$table->string('NOMEFANTASIA')->length(40)->nullable();
			$table->string('RAZAOSOCIAL')->length(40)->nullable();
			$table->string('RAZAOABREV')->length(15);
			$table->integer('CODEMPMATRIZ')->nullable();
			$table->integer('CODEND')->nullable();
			$table->string('NUMEND')->length(6)->nullable();
			$table->string('COMPLEMENTO')->length(10)->nullable();
			$table->integer('CODBAI');
			$table->integer('CODCID')->nullable();
			$table->string('CEP')->length(8)->nullable();
			$table->string('TELEFONE')->length(13)->nullable();
			$table->string('FAX')->length(13)->nullable();
			$table->string('TELEX')->length(12)->nullable();
			$table->string('EMAIL')->length(80)->nullable();
			$table->string('HOMEPAGE')->length(255)->nullable();
			$table->integer('NUMPROPR')->nullable();
			$table->string('PRINCTITULAR')->length(40)->nullable();
			$table->string('CGC')->length(14)->nullable();
			$table->string('INSCESTAD')->length(16)->nullable();
			$table->string('INSCMUN')->length(16)->nullable();
			$table->integer('CODMUN')->nullable();
			$table->integer('NATESTAB')->nullable();
			$table->integer('NATJUR')->nullable();
			$table->string('RAMOATIV')->length(40)->nullable();
			$table->integer('ATIVECON')->nullable();
			$table->string('REGJUNTACOM')->length(12)->nullable();
			$table->date('DTREGJUNTA')->nullable();
			$table->text('LOGOMARCA')->nullable();
			$table->string('FINANCEIRO')->length(1)->default('N' );
			$table->string('ESTOQUE')->length(1)->default('N' );
			$table->string('CARGAS')->length(1)->default('N' );
			$table->string('COMISSOES')->length(1)->default('N' );
			$table->string('PRODUCAO')->length(1)->default('N' );
			$table->string('SUPDECISAO')->length(1)->default('N' );
			$table->string('LIVROSFISCAIS')->length(1)->default('N' );
			$table->date('CONTABILIDADE')->nullable();
			$table->string('FOLHAPAGTO')->length(1)->default('N' );
			$table->string('CODCNL')->length(10)->nullable();
			$table->string('SIMPLES')->length(1)->nullable()->default('N');
			$table->integer('CODPARC')->nullable();
			$table->float('LIMCURVA_B')->nullable();
			$table->float('LIMCURVA_C')->nullable();
			$table->integer('EMPAGRUPARGOL')->nullable();
			$table->string('SERIENFDES')->length(4)->nullable();
			$table->string('MODELONFDES')->length(2)->nullable();
			$table->string('COOPERATIVA')->length(1)->default('N' );
			$table->date('DTCONVSOC')->nullable();
			$table->string('DUPLIV')->length(1)->default('N' );
			$table->string('CPFRESP')->length(11)->nullable();
			$table->integer('CODREGTRIB')->nullable();
			$table->integer('TIPOSN')->nullable();
			$table->integer('CODPARCDIV');
			$table->string('MD5PAF')->length(32)->nullable();
			$table->string('RAZAOSOCIALCOMPLETA')->length(250)->nullable();
			$table->string('SERVIDORSMTP')->length(80)->nullable();
			$table->string('TIPOSMTP')->length(1)->default('N' );
			$table->string('USUARIOSMTP')->length(80)->nullable();
			$table->string('SENHASMTP')->length(80)->nullable();
			$table->integer('PORTASMTP')->default(25);
			$table->string('SEGURANCASMTP')->length(1)->default('N' );
			$table->string('LATITUDE')->length(255)->nullable();
			$table->string('LONGITUDE')->length(255)->nullable();
			$table->string('SIMPLESNACNAUF')->length(1)->default('S' );
			$table->string('DMACODINSP')->length(2)->nullable();
			$table->string('DMAESPECIAL')->length(1)->default('N' );
			$table->date('DTENCERBALAN')->nullable();
			$table->string('CODQUALASSIN')->length(3)->nullable();
			$table->integer('CODPARCRESP')->nullable();
			$table->string('SITESPECIALRESP')->length(2)->nullable();
			$table->string('EXIGEISSQN')->length(2)->nullable();
			$table->string('REGESPTRIBUT')->length(2)->nullable();
			$table->string('RNTRC')->length(8)->nullable();
			$table->integer('CLASSTRIB')->nullable();
			$table->integer('CNAEPREPON')->nullable();
			$table->integer('INDCOOP');
			$table->integer('INDCONSTR');
			$table->integer('INFOOBRA')->nullable();
			$table->integer('CODUSU')->nullable();
			$table->date('DHALTER')->default(SYSDATE );
			$table->integer('ACDINTISENMULTA')->nullable();
			$table->integer('CODPARCEMPSOFT')->nullable();
			$table->integer('CODCTTPARCEMPSOFT')->nullable();
			$table->integer('INDSITESP');
			$table->string('TIPTRANSMNFSE')->length(1)->default('A' );
			$table->integer('COREMPRESA')->nullable()->default(16777215);
			$table->integer('QTDACESSOS')->nullable();
			$table->string('ENVESOCIAL')->length(1)->default('N' );
			$table->string('RECIBOESOCIAL')->length(40)->nullable();
			$table->date('INIVALESOCIAL')->nullable();
			$table->date('FIMVALESOCIAL')->nullable();
			$table->integer('INDOPCCP')->nullable();
			$table->integer('NUVERSAO')->nullable();
			$table->string('USARAZAOSOCIAL')->length(1)->nullable();
			$table->date('DTABERTURA')->nullable();
			$table->string('EMPIDENOTAS')->length(50)->nullable();
			$table->string('PRODUTORRURAL')->length(1)->nullable();
			$table->string('COTM')->length(20)->nullable();
			$table->date('DHCONSITIMEND')->nullable();
			$table->string('NUREST')->length(25)->nullable();
			$table->string('NUMTAF')->length(12)->nullable();
			$table->string('DESCRCENCUS')->length(50);
			$table->integer('CODCENCUSPAI');
			$table->string('ATIVO')->length(1)->default('S' );
			$table->string('ANALITICO')->length(1)->default('S' );
			$table->integer('GRAU');
			$table->integer('CODUSURESP');
			$table->float('AREA')->nullable();
			$table->integer('CODPARC');
			$table->integer('CODTAB');
			$table->date('DTINCLUSAO')->nullable()->default(SYSDATE);
			$table->integer('CODUNN')->nullable();
			$table->float('FRACGEREN')->nullable();
			$table->float('FRACCONT')->nullable();
			$table->float('AREAPERM')->nullable();
			$table->float('AREACONT')->nullable();
			$table->float('AREAREAL')->nullable();
			$table->integer('CODUNG')->nullable();
			$table->string('VEICULO')->length(1)->default('N' );
			$table->integer('CODPARCRESP')->nullable();
			$table->string('CALCELALURPARTEA')->length(1)->nullable();
			$table->string('AD_IDEXTERNO')->length(100)->nullable();
			$table->string('CODCTABCO')->length(17)->nullable();
			$table->string('DESCRICAO')->length(40)->nullable();
			$table->integer('CODBCO')->nullable();
			$table->string('CODAGE')->length(5)->nullable();
			$table->integer('CODEMP')->nullable();
			$table->string('CLASSE')->length(1)->nullable();
			$table->integer('CARTEIRA')->nullable();
			$table->integer('SEQREM')->nullable();
			$table->integer('REMBCO')->nullable();
			$table->integer('REMFINAL')->nullable();
			$table->float('CONVENIO')->nullable();
			$table->integer('INSTRUCAOI')->nullable();
			$table->integer('INSTRUCAOII')->nullable();
			$table->integer('DIASPROT')->nullable();
			$table->string('EMITEBOLETA')->length(1)->default('S' );
			$table->string('IMPBOLETA')->length(32)->nullable();
			$table->integer('MODBOLETA')->nullable();
			$table->integer('CODCTACTB')->nullable();
			$table->string('EXCLUSIVA')->length(1)->default('S' );
			$table->string('ATIVA')->length(1)->default('S' );
			$table->integer('NUMCHEQ')->nullable();
			$table->string('CTADEFEMIBOL')->length(1)->nullable()->default('N');
			$table->float('VLRMINBOLETA')->nullable();
			$table->integer('CTAMINBOLETA')->nullable();
			$table->float('TAXA')->nullable();
			$table->integer('CODPARC');
			$table->string('TIPOIMPRESSORA')->length(1)->default('1' );
			$table->integer('CODOPEREXCL');
			$table->date('DTALTER')->default(SYSDATE );
			$table->date('DTIMPLANT')->nullable();
			$table->float('SALDOBCO')->nullable();
			$table->float('SALDOREAL')->nullable();
			$table->integer('CODMOEDA');
			$table->integer('CODUSU')->nullable();
			$table->integer('REMBCOMAX')->nullable();
			$table->string('ZERARAUT')->length(1)->default('N' );
			$table->integer('CODCTABCOINTREM')->nullable();
			$table->integer('SEQREM2')->nullable();
			$table->integer('REMFINAL2')->nullable();
			$table->integer('NURFEMODCHEQG')->nullable();
			$table->integer('CODCORRBCO')->nullable();
			$table->integer('NUCONTRATO')->nullable();
			$table->integer('MODALIDADE')->nullable();
			$table->integer('CATEGLANCHQ')->nullable();
			$table->string('CAMPOLIVRE')->length(25)->nullable();
			$table->string('NOSSONUMERO')->length(25)->nullable();
			$table->string('MULTIPNOSSONUM')->length(25)->nullable();
			$table->string('TIPMULTIPSOMA')->length(1)->default('T' );
			$table->string('TIPMODNOSSNUM')->length(1)->default('O' );
			$table->string('SUBRESTMODULO')->length(1)->default('N' );
			$table->integer('RESTOSUBST1')->nullable();
			$table->integer('RESTOSUBST2')->nullable();
			$table->integer('RESTOSUBST3')->nullable();
			$table->string('DIGITOSUBST1')->length(1)->nullable();
			$table->string('DIGITOSUBST2')->length(1)->nullable();
			$table->string('DIGITOSUBST3')->length(1)->nullable();
			$table->string('NOSSONUMATIVO')->length(1)->default('N' );
			$table->string('LINHADIGATIVO')->length(1)->default('N' );
			$table->integer('NUMCLIENTE')->nullable();
			$table->string('IDCLIENTE')->length(30)->nullable();
			$table->integer('CODAGEBENEF')->nullable();
			$table->integer('CODCTABENEF')->nullable();
			$table->integer('CODCTABAIXA')->nullable();
			$table->string('PJBCRED')->length(80)->nullable();
			$table->string('PJBCHAVE')->length(80)->nullable();
			$table->string('BJBBAIBOLPAG')->length(1)->nullable();
			$table->string('PJBCONBAIXCRED')->length(1)->nullable();
			$table->integer('CODLANCBAIXABOLRAP')->nullable();
			$table->integer('CODTIPOPERBAIXABOLRAP')->nullable();
			$table->string('TIPOBOLETO')->length(1)->nullable();
			$table->string('CODCONTARURAL')->length(3)->nullable();
			$table->string('DESCONSLCDPR')->length(1)->nullable();
			$table->string('LOGOURL')->length(4000)->nullable();
			$table->string('NUMCONTARURAL')->length(3)->nullable();
			$table->string('CHAVEPIX')->length(77)->nullable();
			$table->string('URLPIX')->length(300)->nullable();
			$table->integer('QTDDIASVALPIX')->nullable();
			$table->integer('NURFEMODBOLETO')->nullable();
			$table->string('CHAVEAPIPIX')->length(250)->nullable();
			$table->string('TITINFADICPIX')->length(50)->nullable();
			$table->string('MENADICPIX')->length(300)->nullable();
			$table->string('SENCLIPIX')->length(1000)->nullable();
			$table->string('IDCLIPIX')->length(250)->nullable();
			$table->string('CONCAUTRECEBPIX')->length(1)->nullable();
			$table->integer('IDAPIBANCO')->nullable();
			$table->string('INDICADORPIX')->length(2)->nullable();
			$table->integer('VARIACAO')->nullable();
			$table->string('ACEITATITULOVENCIDO')->length(32)->nullable();
			$table->string('TIPOAPIBOLETO')->length(1)->nullable();
			$table->string('STATUSAPI')->length(32)->nullable();
			$table->integer('RECEBIMENTODIAS')->nullable();
			$table->string('RECEBIMENTOPARCIAL')->length(32)->nullable();
			$table->string('APICONCILIACAOAUTOMATICA')->length(1)->nullable();
			$table->string('APIBAIXAAUTOMATICA')->length(1)->nullable();
			$table->date('DTREGCONTA')->nullable();
			$table->integer('DIASPARANEGATIVACAO')->nullable();
			$table->integer('ORGAONEGATIVADOR')->nullable();
			$table->integer('DIASPROTESTO')->nullable();
			$table->integer('DIASMULTA')->nullable();
			$table->integer('VALORMULTA')->nullable();
			$table->string('DATAMULTA')->length(1)->nullable();
			$table->string('TIPOMULTA')->length(1)->nullable();
			$table->integer('VALORJUROS')->nullable();
			$table->string('TIPOJUROS')->length(1)->nullable();
			$table->integer('INSTRUCAOPROTESTO')->nullable();
			$table->string('CONTABILIZARDIAS')->length(1)->nullable();
			$table->integer('INSTRUCAONEGATIVACAO')->nullable();
			$table->integer('IDSEQBOL')->nullable();
			$table->string('ABREVIATURA')->length(15);
			$table->string('NOMEBCO')->length(40);
			$table->integer('CTACMC7INI')->nullable();
			$table->integer('CTACMC7FIM')->nullable();
			$table->integer('CODTAB');
			$table->date('DTVIGOR');
			$table->integer('CODREG')->nullable();
			$table->date('DTALTER');
			$table->float('PERCENTUAL')->nullable();
			$table->string('FORMULA')->length(4000)->nullable();
			$table->integer('CODTABORIG')->nullable();
			$table->string('JAPE_ID')->length(50)->nullable();
			$table->string('UTILIZADECCUSTO')->length(1)->nullable();
			$table->string('DESCRCFO')->length(30);
			$table->integer('CODCTACTB')->nullable();
			$table->integer('GRUPOCFO')->nullable();
			$table->string('CONVPRODUZ')->length(1)->default('N' );
			$table->string('TRIBUTADASCIAP')->length(1)->default('N' );
			$table->string('TIPICMS')->length(1)->default('1' );
			$table->string('CALCDIFICMS')->length(1)->default('S' );
			$table->string('TIPO')->length(1)->nullable();
			$table->string('RECBRUTAEFDBLOCOP')->length(1)->default('N' );
			$table->string('COP')->length(4)->nullable();
			$table->string('PARTDIEF')->length(1)->nullable()->default('N');
			$table->string('CALCICMSCOMPL')->length(1)->default('N' );
			$table->string('TIPOPERPRODEPE')->length(1)->nullable();
			$table->string('EMPCODSIT08EFD')->length(200)->nullable();
			$table->string('MOVIMFISICA')->length(1)->nullable();

		});
	}

	public function down()
	{
		Schema::dropIfExists('{table_name}');
	}
}