<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tgffin', function (Blueprint $table) {
          $table->integer('NUFIN')->length(22)->primary();
          $table->integer('CODEMP')->length(22);
          $table->integer('NUMNOTA')->length(22);
          $table->string('SERIENOTA')->length(3)->nullable();
          $table->date('DTNEG')->length(7)->format('d/m/Y');
          $table->string('DESDOBRAMENTO')->length(2)->nullable();
          $table->datetime('DHMOV')->length(7)->format('d/m/Y H:i:s');
          $table->datetime('DTVENCINIC')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->date('DTVENC')->length(7)->nullable()->format('d/m/Y');
          $table->date('DHBAIXA')->length(7)->nullable()->format('d/m/Y');
          $table->datetime('DTCONTAB')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->datetime('DTCONTABBAIXA')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->integer('CODPARC')->length(22);
          $table->integer('CODTIPOPER')->length(22)->default(0);
          $table->datetime('DHTIPOPER')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->integer('CODBCO')->length(22)->default(0);
          $table->integer('CODCTABCOINT')->length(22)->nullable();
          $table->integer('CODNAT')->length(22);
          $table->integer('CODCENCUS')->length(22)->default(0);
          $table->integer('CODPROJ')->length(22)->nullable()->default(0);
          $table->integer('CODVEND')->length(22)->default(0);
          $table->integer('CODMOEDA')->length(22)->default(0);
          $table->integer('CODTIPTIT')->length(22)->default(0);
          $table->integer('NUMDUPL')->length(22)->nullable();
          $table->string('DESDOBDUPL')->length(2)->nullable();
          $table->string('NOSSONUM')->length(12)->nullable();
          $table->string('HISTORICO')->length(255)->nullable();
          $table->float('VLRDESDOB')->length(22);
          $table->float('VLRVENDOR')->length(22)->default(0);
          $table->float('VLRIRF')->length(22)->default(0);
          $table->float('VLRISS')->length(22)->default(0);
          $table->float('VLRCHEQUE')->length(22)->nullable();
          $table->float('DESPCART')->length(22)->default(0);
          $table->string('ISSRETIDO')->length(1)->default('N');
          $table->float('VLRDESC')->length(22)->default(0);
          $table->float('VLRMULTA')->length(22)->default(0);
          $table->float('VLRINSS')->length(22)->default(0);
          $table->string('TIPMULTA')->length(1)->nullable()->default('1');
          $table->float('VLRJURO')->length(22)->default(0);
          $table->string('TIPJURO')->length(1)->nullable()->default('1');
          $table->float('BASEICMS')->length(22)->default(0);
          $table->float('ALIQICMS')->length(22)->default(0);
          $table->integer('CODEMPBAIXA')->length(22)->nullable();
          $table->integer('CODTIPOPERBAIXA')->length(22)->default(0);
          $table->datetime('DHTIPOPERBAIXA')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->float('VLRBAIXA')->length(22)->default(0);
          $table->integer('NUMREMESSA')->length(22)->nullable();
          $table->string('AUTORIZADO')->length(1)->default('N');
          $table->integer('RECDESP')->length(22)->default(0);
          $table->string('PROVISAO')->length(1)->default('N');
          $table->string('ORIGEM')->length(1)->default('F');
          $table->string('TIPMARCCHEQ')->length(1)->default('A');
          $table->integer('NUNOTA')->length(22)->nullable();
          $table->integer('NUBCO')->length(22)->nullable();
          $table->integer('NUDEV')->length(22)->nullable();
          $table->integer('NURENEG')->length(22)->nullable();
          $table->integer('CARTA')->length(22)->nullable();
          $table->string('RATEADO')->length(1)->default('N');
          $table->date('DTENTSAI')->length(7)->nullable()->format('d/m/Y');
          $table->integer('CODUSUBAIXA')->length(22)->nullable();
          $table->float('VLRPROV')->length(22)->default(0);
          $table->string('IRFRETIDO')->length(1)->nullable()->default('N');
          $table->string('INSSRETIDO')->length(1)->default('N');
          $table->float('CARTAODESC')->length(22)->nullable()->default(0);
          $table->datetime('DTALTER')->length(7)->format('d/m/Y H:i:s');
          $table->integer('NUMCONTRATO')->length(22)->default(0);
          $table->integer('ORDEMCARGA')->length(22)->default(0);
          $table->integer('CODVEICULO')->length(22)->default(0);
          $table->string('CODBARRA')->length(50)->nullable();
          $table->integer('CODUSU')->length(22)->default(0);
          $table->integer('SEQUENCIA')->length(22)->nullable();
          $table->float('VLRVARCAMBIAL')->length(22)->nullable();
          $table->string('CODIGOBARRA')->length(55)->nullable();
          $table->string('LINHADIGITAVEL')->length(57)->nullable();
          $table->float('VLRDESCEMBUT')->length(22)->nullable()->default(0);
          $table->float('VLRJUROEMBUT')->length(22)->nullable()->default(0);
          $table->float('VLRMULTAEMBUT')->length(22)->nullable()->default(0);
          $table->float('VLRMOEDA')->length(22)->nullable()->default(0);
          $table->float('VLRMOEDABAIXA')->length(22)->nullable()->default(0);
          $table->integer('NUCOMPENS')->length(22)->nullable();
          $table->integer('CODCFO')->length(22)->nullable();
          $table->float('VLRMULTANEGOC')->length(22)->nullable()->default(0);
          $table->float('VLRJURONEGOC')->length(22)->nullable()->default(0);
          $table->float('VLRMULTALIB')->length(22)->nullable()->default(0);
          $table->float('VLRJUROLIB')->length(22)->nullable()->default(0);
          $table->datetime('DTBAIXAPREV')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->integer('NUMOS')->length(22)->nullable();
          $table->string('NATUREZAOPERDES')->length(2)->nullable();
          $table->string('SERIENFDES')->length(4)->nullable();
          $table->string('MODELONFDES')->length(2)->nullable();
          $table->integer('CODFUNC')->length(22)->nullable();
          $table->integer('CODCONTATO')->length(22)->nullable();
          $table->integer('NUAPONTA')->length(22)->nullable();
          $table->integer('NUMBOR')->length(22)->nullable();
          $table->float('M2')->length(22)->nullable();
          $table->string('DIGSAFRA')->length(1)->nullable();
          $table->string('NFENTSEQFIX')->length(15)->nullable();
          $table->integer('NFCOMPLFIX')->length(22)->nullable();
          $table->string('PDD')->length(1)->nullable();
          $table->integer('CODUSUCOBR')->length(22)->nullable();
          $table->string('NUMNFSE')->length(20)->nullable();
          $table->float('VLRALIBERAR')->length(22)->nullable();
          $table->string('CHAVECTE')->length(44)->nullable();
          $table->string('CHAVECTEREF')->length(44)->nullable();
          $table->string('NOMEEMITENTE_CMC7')->length(160)->nullable();
          $table->float('VLRCESSAO')->length(22)->nullable();
          $table->integer('IDLOTEFDIC')->length(22)->nullable();
          $table->integer('NUPED')->length(22)->nullable();
          $table->integer('CODBCO_CMC7')->length(22)->nullable();
          $table->string('AGENCIA_CMC7')->length(5)->nullable();
          $table->string('CONTA_CMC7')->length(14)->nullable();
          $table->string('CGC_CPF_CMC7')->length(14)->nullable();
          $table->integer('CODCC')->length(22)->nullable();
          $table->string('SITESPECIALRESP')->length(2)->nullable();
          $table->string('EXIGEISSQN')->length(2)->nullable();
          $table->string('REGESPTRIBUT')->length(2)->nullable();
          $table->string('MOTNAORETERISSQN')->length(2)->nullable();
          $table->float('VLRFATCARTAO')->length(22)->nullable();
          $table->integer('NUCCR')->length(22)->nullable();
          $table->integer('NROLOTEGNRE')->length(22)->nullable();
          $table->string('STATUSGNRE')->length(50)->nullable();
          $table->string('REJEICAOGNRE')->length(500)->nullable();
          $table->integer('NUFTC')->length(22)->nullable();
          $table->string('PARCRENEG')->length(20)->nullable();
          $table->string('TPAGNFCE')->length(2)->nullable();
          $table->float('VALORPRESENTE')->length(22)->nullable();
          $table->float('JUROSAVP')->length(22)->nullable();
          $table->string('BLOQVAR')->length(1)->nullable()->default('N');
          $table->float('VLRDESCCALC')->length(22)->nullable();
          $table->float('BASEIRF')->length(22)->nullable();
          $table->float('BASEINSS')->length(22)->nullable();
          $table->string('MONIOCOREM')->length(1)->nullable();
          $table->date('DTPRAZO')->length(7)->nullable()->format('d/m/Y');
          $table->string('RECEBCARTAO')->length(1)->nullable();
          $table->float('ABATIMENTO')->length(22)->nullable();
          $table->float('ABATIMENTOCAN')->length(22)->nullable();
          $table->integer('CODCBE')->length(22)->nullable();
          $table->string('DESPADVOGADO')->length(1)->nullable();
          $table->string('CUSTASPROCESSUAIS')->length(1)->nullable();
          $table->string('DEPOSITOJUDICIAL')->length(1)->nullable();
          $table->string('NUMPROCADMJUDIC')->length(21)->nullable();
          $table->integer('OBRACONSTCIVIL')->length(22)->nullable();
          $table->integer('CLASSIFCESSAOOBRA')->length(22)->nullable();
          $table->integer('CODLST')->length(22)->nullable();
          $table->integer('CODTRIB')->length(22)->nullable();
          $table->integer('CODCIDINICTE')->length(22)->nullable();
          $table->integer('CODCIDFIMCTE')->length(22)->nullable();
          $table->string('CODOBRA')->length(15)->nullable();
          $table->string('CHEQUERASTREADO_CMC7')->length(1)->nullable();
          $table->integer('NUCHQ')->length(22)->nullable();
          $table->integer('CODREGUA')->length(22)->nullable();
          $table->integer('IDUNICO')->length(22)->nullable();
          $table->integer('SEQCAIXA')->length(22)->nullable();
          $table->integer('TIMPARCELA')->length(22)->nullable();
          $table->integer('TIMCONTRATOLOC')->length(22)->nullable();
          $table->integer('TIMNEGOCIACAO')->length(22)->nullable();
          $table->datetime('TIMDTIMPBOL')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->date('TIMDTREPASSE')->length(7)->nullable()->format('d/m/Y');
          $table->datetime('TIMDHBAIXA')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->datetime('TIMDATADEJUR')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->integer('TIMNUMREG')->length(22)->nullable();
          $table->string('TIMORIGEM')->length(2)->nullable();
          $table->integer('TIMNUFINORIG')->length(22)->nullable();
          $table->integer('TIMVENDAIMV')->length(22)->nullable();
          $table->integer('TIMRENEGIMV')->length(22)->nullable();
          $table->integer('TIMVENDALOTE')->length(22)->nullable();
          $table->integer('TIMRENEGLOTE')->length(22)->nullable();
          $table->integer('TIMSAC')->length(22)->nullable();
          $table->string('TIMNOMEADVOGADO')->length(200)->nullable();
          $table->datetime('TIMDHGERREPASSE')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->integer('TIMCONTAREP')->length(22)->nullable();
          $table->integer('TIMIMOVEL')->length(22)->nullable();
          $table->integer('TIMCONTRATOADM')->length(22)->nullable();
          $table->string('TIMBLOQUEADA')->length(1)->nullable()->default('N');
          $table->integer('TIMFECHAMENTOALU')->length(22)->nullable();
          $table->datetime('TIMDTIMPBOLLOCAL')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->integer('TIMFECHAMENTO')->length(22)->nullable();
          $table->integer('TIMRENEGCANCLOTE')->length(22)->nullable();
          $table->integer('TIMCONTRATOLTV')->length(22)->nullable();
          $table->integer('TIMRESCISAOLTV')->length(22)->nullable();
          $table->integer('TIMCONTALANC')->length(22)->nullable();
          $table->string('TIMTXADMGERALU')->length(1)->nullable()->default('S');
          $table->integer('TIMFINGARANTORIG')->length(22)->nullable();
          $table->integer('TIMREPINTELIGENTE')->length(22)->nullable();
          $table->datetime('TIMDHGERREPPARCIAL')->length(7)->nullable()->format('d/m/Y H:i:s');
          $table->date('TIMDTREPPARCIAL')->length(7)->nullable()->format('d/m/Y');
          $table->string('TIMREPPARCIAL')->length(1)->nullable();
          $table->float('TIMVLRJUROCONTRATO')->length(22)->nullable();
          $table->float('TIMVLRAMORTCONTRATO')->length(22)->nullable();
          $table->float('TIMVLRCORRMONET')->length(22)->nullable();
          $table->integer('CODIPTU')->length(22)->nullable();
          $table->string('TIMORIGRENEG')->length(1)->nullable();
          $table->integer('TIMRESCISAOLOC')->length(22)->nullable();
          $table->integer('TIMTIPOINTERMED')->length(22)->nullable();
          $table->integer('CODOBSPADRAO')->length(22)->nullable();
          $table->integer('NUCKC')->length(22)->nullable();
          $table->string('ISINTEGRADOFERCUS')->length(1)->nullable();
          $table->float('VLRLIQUIDO')->length(22);
          $table->integer('VLRTOTALCALC')->nullable();
          $table->float('VLRTROCO')->nullable();
          $table->string('AD_STATUSBOLETO')->nullable();
          $table->string('AD_NRNF')->nullable();
          $table->string('AD_IDEXTERNO')->nullable();
          $table->text('AD_ID_EXTERNO_CODPARC')->nullable();
          $table->text('AD_ID_EXTERNO_CODNAT')->nullable();
          $table->text('AD_ID_EXTERNO_CODEMP')->nullable();
          $table->text('AD_DOCSREF')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tgffin');
    }
};
