CREATE OR REPLACE FORCE VIEW "VW_STPEDIDOS_JSON" ("NUNOTA","STATUSNOTA","DESCRICAO","DTALTER") AS 
SELECT CAB.NUNOTA,CAB.STATUSNOTA--pega todos os pedidos 
    ,CASE WHEN CAB.STATUSNOTA = 'P' THEN 'Pedente'
        WHEN CAB.STATUSNOTA = 'L' THEN 'Liberado'
        WHEN CAB.STATUSNOTA = 'A' THEN 'Atendimento' END AS DESCRICAO
    ,CAB.DTALTER    
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'P'
UNION ALL
SELECT EXC.NUNOTA--pega todos os pedidos cancelados
, STATUSNOTA, 'Cancelado' AS DESCRICAO, EXC.DTALTER 
FROM TGFCAB_EXC EXC,TGFCAN C
WHERE EXC.TIPMOV = 'P'
AND C.NUNOTA = EXC.NUNOTA